---
title: "2024 Home Economy"
author: '[Brody Moore](mailto:bmoore1@snapfinance.com)'
date: "`r format(Sys.time(),'%B %d, %Y @ %I:%M%p')`"
output:
  rmdformats::readthedown:
  highlight: tango
toc_depth: 3
use_bookdown: TRUE
---
  
```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

library(tidyverse)
library(reactable)
library(highcharter)
library(stringr)
library(shiny)
library(lubridate)
opts <- getOption("highcharter.lang")
opts$thousandsSep <- ","
options(highcharter.lang = opts)

## Global options
opts_chunk$set(
  # eval = FALSE, # uncomment this when first publishing to add credentials
  echo = FALSE,
  cache = FALSE,
  prompt = FALSE,
  tidy = FALSE,
  comment = NA,
  message = FALSE,
  warning = FALSE
)
```

```{r define_helpful_functions}

breakdown_function <- function(data) {
  data %>%
    mutate(place = if_else(category == "restaurant", "restaurant", place)) %>% 
    group_by(category, place) %>% 
    summarise(amt_spent = sum(amount)) %>% 
    group_by(category) %>% 
    mutate(category_spent = sum(amt_spent)) %>% 
    arrange(desc(category_spent), desc(amt_spent))
}

category_function <- function(data, month) {
  summarised_data <- data %>% 
    group_by(category) %>% 
    summarise(!!(paste0("amt_spent_",{{ month }})) := sum(amount)) 
  
  summarised_data %>% 
    arrange(desc(UQ(sym(names(summarised_data)[2]))))
}

prep_roll_up_function <- function(data) {
  fixed_categories <- c("subscription", "house_essential", "subscripiton", "family", "renewal_fee", "house_payment", "subscription", "car")
  
  data %>% 
    group_by(category, place) %>% 
    summarise(amount = sum(amount)) %>% 
    ungroup() %>% 
    mutate(summarised_category = if_else(category %in% fixed_categories, "Fixed", "Controlable"))
}

wrap_up_reactable <- function(data) {
  prepped_data <- prep_roll_up_function(data)
  
  reactable(
    prepped_data ,
    groupBy = c("summarised_category", "category"),
    columns = list(
      amount = colDef(
        name = "Amount",
        aggregate = "sum", 
        format = colFormat(currency = "USD"),
        footer = function(values) sprintf("$%.2f", sum(values))
      ),
      place = colDef(name = "Place"),
      category = colDef(name = "Category"),
      summarised_category = colDef(name = "Summarised Category", footer = "Total")
    ),
    defaultSorted = list(amount = "desc")
  )
}

specific_vaca_function <- function(data, former_year_vaca, vacation_text) {
  data %>% 
    bind_rows(former_year_vaca) %>% 
    filter(category == vacation_text) %>% 
    mutate(
      defined_category = gsub(".*?\\((.*?)\\).*?", "\\1", place),
      place = gsub("\\s*\\(.*\\)", "", place)
    ) %>% 
    group_by(defined_category) %>% 
    mutate(tot_amt = sum(amount)) %>% 
    ungroup() %>% 
    arrange(desc(tot_amt)) %>% 
    select(defined_category, place, amount)
}

specific_vaca_reactable <- function(data) {
  reactable(
  data,
  groupBy = c("defined_category"),
  columns = list(
    amount = colDef(
      aggregate = "sum", 
      format = colFormat(currency = "USD"), 
      footer = function(values) sprintf("$%.2f", sum(values))),
    defined_category = colDef(footer = "Total")
  )
)
}
```

<!-- Income Documentation -->
  
```{r income}
# Things like making money from a category that we already spent money on doesn't go in here. Only earned income from salary or side gigs.

num_months_that_occured <- month(today())

reoccuring_income <- tibble(
  month = month.abb[1:num_months_that_occured],
  source = rep("snap", num_months_that_occured),
  amount = rep((3336 + 588) * 2, num_months_that_occured)
)

variable_income <- tribble(
  ~month,  ~source, ~amount,
  "Apr",   "snap",   8000,
  "Nov",   "uepc",    930,
  "Oct",   "uepc",   1113,
  "Dec",   "uepc",    712,
  "Dec",   "refund", 1800,
  "Dec",   "xmas",   1550
)

stacked_income <- reoccuring_income %>% 
  bind_rows(variable_income) %>% 
  arrange(month)

combined_income <- stacked_income %>% 
  group_by(month) %>% 
  summarise(amount = sum(amount)) %>%
  ungroup() %>% 
  mutate(month = factor(month, levels = month.abb)) %>% 
  arrange(month)

#combined_income %>% 
#  summarise(sum(amount))

```

<!-- Monthly Data Load -->
  
```{r jan}
# jan Purchases -------------------------------------------------------

jan_purchases <- tribble(
  ~place,          ~amount, ~category,
  "krystal",        116.00, "subscription",
  "costco",         166.61, "house_var",
  "dominion",       132.34, "house_essential",
  "winco",           27.92, "grocery",
  "hoa",             60.00, "house_essential",
  "costco",           2.90, "restaurant",
  "ginnys",           7.54, "restaurant",
  "zupas",            9.77, "restaurant",
  "zupas",           13.49, "restaurant",
  "great_clips",     26.00, "personal",
  "maverik",          2.26, "restaurant",
  "wal_mart",         16.13, "misc",
  "super_chix",      17.26, "restaurant",
  "maceys",          27.84, "grocery",
  "hobby_lobby",     36.85, "bunco",
  "chilis",           6.47, "restaurant",
  "amazon",          16.08, "subscription",
  "maverik",         32.15, "gas",
  "phillips_66",      7.80, "restaurant",
  "eagle_point",    126.01, "snowboarding",
  "creamery",        15.17, "restaurant",
  "eagle_point",      5.32, "snowboarding",
  "maverik",         28.83, "gas",
  "sinclair_oil",    48.14, "gas",
  "zurchers",        11.47, "bunco",
  "wal_mart",         18.15, "bunco",
  "chilis",          12.94, "bunco",
  "bath_body_works", 10.10, "bunco",
  "valvoline",       44.98, "car",
  "brutus_loan",    350.00, "debt",
  "brutus_reg",     151.00, "car",
  "maverik",          2.31, "restaurant",
  "zupas",           26.98, "restaurant",
  "groupon",         71.25, "car",
  "wal_mart",         26.21, "house_var",
  "pho_cali",        15.00, "restaurant",
  "panda_express",    7.00, "restaurant",
  "maceys",          19.62, "grocery",
  "amazon",         122.91, "baby",
  "sams_club",       29.68, "gas",
  "sams_club",      127.80, "baby",
  "thai_house",      27.97, "restaurant",
  "panda_express",    5.83, "restaurant",
  "chick_fila",      13.61, "restaurant",
  "amazon",         171.19, "josie_bday",
  "amazon",           9.58, "baby",
  "wal_mart",         76.79, "misc",
  "lucky_slice",     16.25, "restaurant",
  "smiths",          45.90, "grocery",
  "sierra",         123.04, "clothes",
  "sams_club",       21.15, "gas",
  "wal_mart",         13.87, "misc",
  "in_n_out",         7.99, "restaurant",
  "homegoods",       10.69, "house_var",
  "adobe",           10.69, "subscription",
  "maceys",           9.67, "grocery",
  "amazon",          38.92, "baby",
  "tj_maxx",         29.94, "clothes",
  "target",          33.16, "baby",
  "locals",          26.74, "personal",
  "five_guys",       26.74, "restaurant",
  "chick_fila",      10.56, "restaurant",
  "smiths",          30.40, "grocery",
  "zupas",           26.98, "restaurant",
  "apple",            7.50, "subscription",
  "target",          21.45, "misc",
  "mandarin_garden", 12.69, "restaurant",
  "ring",            39.99, "subscription",
  "ramen_haus",      28.00, "restaurant",
  "maverik",         28.33, "gas",
  "harmons",         16.18, "grocery",
  "twirl",          135.03, "clothes",
  "nielsens",         8.19, "restaurant",
  "roku_disney",     15.01, "subscription",
  "chip",            13.93, "restaurant",
  "quantum_fiber",   75.00, "house_essential",
  "rocky_mountain",  44.72, "house_essential",
  "nibley_city",    107.49, "house_essential",
  "planet_fitness",  10.70, "subscription",
  "winco",           17.41, "grocery",
  "mortgage",      3487.68, "house_payment",
  "ginnys",           7.54, "restaurant",
  "great_harvest",    5.71, "restaurant",
  "jamba",            7.23, "restaurant",
  "dominos",         19.43, "restaurant",
  "panda_express",   18.04, "restaurant",
  "apple",            2.99, "subscription",
  "quick_quack",     41.99, "subscription",
  "old_navy",        45.96, "baby",
  "amazon",          26.74, "baby",
  #"sams_club",      112.17, "misc",
  "sams_club",       34.45, "grocery",
  "sams_club",       77.72, "baby",
  "noodles",         24.08, "restaurant",
  "in_n_out",        15.98, "restaurant",
  "wendys",           2.48, "restaurant",
  "tubby_todd",      66.35, "baby",
  "sp_kloudy_kids",  34.32, "baby",
  "maverik",         24.17, "gas",
  "harmons",         23.69, "grocery",
  "sams_club",        7.19, "grocery",
  "raising_canes",   12.94, "restaurant",
  "ihc",             21.15, "new_baby",
  "apple",           10.99, "subscription",
  "nothing_bundt",   80.63, "josie_bday",
  "taco_time",       19.07, "restaurant",
  "zurchers",        23.65, "josie_bday",
  "chick_fila",      70.63, "josie_bday",
  "jamba",           15.54, "restaurant",
  "zupas",           14.03, "restaurant",
  "super_chix",       9.49, "restaurant",
  "locals",          17.11, "baby",
  "maverik",         20.76, "gas",
  "student_loans",  336.10, "debt",
  "allstate",        11.50, "house_essential",
  
  # Breakdown Texas
  "drury_inn (extra hotel)",      232.80, "vacation_san_antonio"
) %>% 
  mutate(month = "jan")

jan_breakdown <- breakdown_function(jan_purchases)

jan_categories <- category_function(jan_purchases, "jan")


```

```{r feb}
# feb Purchases -------------------------------------------------------

feb_purchases <- tribble(
  ~place,          ~amount, ~category,
  "krystal",        116.00, "subscription",
  "smiths",           8.03, "personal",
  "maverik",         30.38, "gas",
  "harmons",          2.77, "personal",
  "cafe_rio",        11.27, "restaurant",
  "amazon",          16.08, "subscription",
  "ffb",             49.99, "football",
  "cutler_cookie",   17.59, "restaurant",
  "yeezy",           36.40, "clothes",
  "adobe",           10.69, "subscription",
  "dominion",       139.91, "house_essential",
  "adobe",           10.69, "subscription",
  "sams_club",       32.93, "grocery",
  "sams_club",        5.76, "restaurant",
  "zupas",           14.03, "restaurant",
  "cold_stone",       7.78, "restaurant",
  "arbys",           16.33, "restaurant",
  "maceys",           3.28, "personal",
  "amazon",          31.39, "valentines",
  "amazon",          26.80, "valentines",
  "costa_vida",       8.09, "restaurant",
  "taco_time",        7.24, "restaurant",
  "bowmans",         57.33, "valentines",
  "wal_mart",          1.69, "grocery",
  "maverik",         31.87, "gas",
  "apple",            7.85, "subscription",
  "in_n_out",        37.02, "becks_kids",
  "coca_cola",        2.50, "becks_kids",
  "spitz",           16.89, "restaurant",
  "smiths",          14.81, "grocery",
  "cheveron",         4.12, "restaurant",
  "airborne",        61.10, "becks_kids",
  "amazon",          20.37, "house_var",
  "scheels",         64.35, "clothes",
  "handels",         11.79, "restaurant",
  "raising_canes",    4.58, "restaurant",
  "millcreek",        5.00, "hiking",
  "maverik",         34.82, "gas",
  "habanero_express", 8.68, "restaurant",
  "wal_mart",         15.64, "misc",
  "target",          76.04, "personal",
  "scheels",         35.36, "clothes",
  "qulited_bear",    60.04, "new_baby",
  "zupas",           15.74, "restaurant",
  "sonic",            3.24, "restaurant",
  "roku_disney",     15.01, "subscription",
  "pretty_bird",     18.22, "restaurant",
  "in_n_out",         8.01, "restaurant",
  "pho_cali",        15.00, "restaurant",
  "chick_fila",       7.21, "restaurant",
  "maverik",         29.61, "gas",
  "wal_mart",         40.07, "misc",
  "quick_quack",     41.99, "subscription",
  "jersey_mikes",    15.11, "restaurant",
  "cv_draper",       20.00, "misc",
  "trader_joes",     15.63, "grocery",
  "taco_mall",       10.55, "restaurant",
  "taco_bell",        8.51, "restaurant",
  "apple",            2.99, "subscription",
  #"target",          63.58, "misc",
  "target",          30.28, "house_var",
  "target",          33.30, "baby",
  "nielsens",         5.17, "restaurant",
  "kneaders",         1.61, "restaurant",
  "hires_big_h",     10.37, "restaurant",
  "jimmy_johns",      8.65, "restaurant",
  "maverik",         37.76, "gas",
  "harmons",         53.15, "grocery",
  "wal_mart",        52.41, "grocery",
  "logans_heroes",   23.25, "restaurant",
  "lees_market",     46.85, "grocery",
  "cold_stone",       7.51, "restaurant",
  "apple",           10.99, "subscription",
  "amazon",          10.69, "baby",
  "panda_express",   18.58, "restaurant",
  "fiiz",             3.29, "restaurant",
  "wendys",           7.95, "restaurant",
  "old_grist_mills", 17.63, "restaurant",
  "twisted_sugar",    7.01, "restaurant",
  "old_navy",         8.54, "new_baby",
  "sierra",          37.45, "clothes",
  "homegoods",        4.27, "house_var",
  "wal_mart",         53.03, "misc",
  "wal_mart",         10.67, "church",
  "zao",             21.65, "restaurant",
  "student_loans",  336.10, "debt",
  "quantum_fiber",   75.00, "house_essential",
  "allstate",        11.50, "house_essential",
  "costco",           5.07, "restaurant",
  "nibley_city",    107.49, "house_essential",
  "rocky_mountain",  47.11, "house_essential",
  "planet_fitness",  10.70, "subscription",
  "mortgage",      3856.79, "house_payment",
  "hoa",             60.00, "house_essential",
  
  # Breakdown Texas
  "interval (hotel week)",        79.00, "vacation_san_antonio",
  "maverik (restaurant)",          2.46, "vacation_san_antonio",
  "unita_brewing (restaurant)",    6.53, "vacation_san_antonio",
  "whataburger (restaurant)",     17.94, "vacation_san_antonio",
  "in_n_out (restaurant)",         3.46, "vacation_san_antonio",
  "botanical_garden (experience)",12.00, "vacation_san_antonio",
  "voodoo_doughnut (restaurant)", 11.75, "vacation_san_antonio",
  "terry_blacks (restaurant)",    44.37, "vacation_san_antonio",
  "sonic (restaurant)",            5.70, "vacation_san_antonio",
  "p_terry (restaurant)",          3.70, "vacation_san_antonio",
  "mi_casa (restaurant)",         19.38, "vacation_san_antonio",
  "scruffys (restaurant)",         6.40, "vacation_san_antonio",
  "target (personal)",          63.82, "vacation_san_antonio",
  "parking (parking)",         10.00, "vacation_san_antonio",
  "cici_pizza (restaurant)",       9.19, "vacation_san_antonio",
  "target (personal)",         104.56, "vacation_san_antonio",
  "kfc (restaurant)",              3.56, "vacation_san_antonio",
  "jersey_mikes (restaurant)",    11.73, "vacation_san_antonio",
  "heb_grocery (grocery)",     70.67, "vacation_san_antonio",
  "bucees (restaurant)",          85.95, "vacation_san_antonio",
  "thai_hut (restaurant)",        37.65, "vacation_san_antonio",
  "taqueria_nuevo (restaurant)",  14.06, "vacation_san_antonio",
  "shell_oil (gas)",       18.73, "vacation_san_antonio",
  "shell (restaurant)",            5.60, "vacation_san_antonio",
  "casa_rio (restaurant)",        50.26, "vacation_san_antonio",
  "parking (parking)",         15.00, "vacation_san_antonio",
  "dunkin (restaurant)",           7.56, "vacation_san_antonio",
  "san_antonio_zoo (experience)", 56.24, "vacation_san_antonio",
  "viva_satx (experience)",       14.06, "vacation_san_antonio",
  "quiktrip (restaurant)",         8.54, "vacation_san_antonio",
  "parking (parking)",         25.00, "vacation_san_antonio",
  "five_and_dime (souvenier)",   11.90, "vacation_san_antonio",
  "dough_pizza (restaurant)",     43.00, "vacation_san_antonio",
  "parking (parking)",         15.00, "vacation_san_antonio",
  "henry_puffy_taco (restaurant)",23.00, "vacation_san_antonio",
  "chick_fila (restaurant)",       4.93, "vacation_san_antonio",
  "auntie_annes (restaurant)",    14.58, "vacation_san_antonio",
  "voodoo_doughnut (restaurant)",  7.00, "vacation_san_antonio",
  "target (personal)",          60.08, "vacation_san_antonio",
  "sichuan_house (restaurant)",   45.98, "vacation_san_antonio",
  "parking (parking)",         10.00, "vacation_san_antonio",
  "party_city (misc)",      32.91, "vacation_san_antonio",
  "marble_slab (restaurant)",     12.97, "vacation_san_antonio",
  "mattengas_pizza (restaurant)", 35.16, "vacation_san_antonio",
  "soup_peddler (restaurant)",    21.37, "vacation_san_antonio",
  "popeyes (restaurant)",         11.24, "vacation_san_antonio",
  "mi_casa (restaurant)",         32.42, "vacation_san_antonio",
  "girl_scout (grocery)",       5.00, "vacation_san_antonio",
  "bucees (gas)",          22.77, "vacation_san_antonio",
  "bucees (restaurant)",          43.02, "vacation_san_antonio",
  "la_quinta (extra hotel)",      106.41, "vacation_san_antonio",
  "fox_rental_car (rental car)", 456.70, "vacation_san_antonio",
  "exxonmobil (restaurant)",       4.97, "vacation_san_antonio",
  "austin_airport (restaurant)",   5.40, "vacation_san_antonio"
) %>% 
  mutate(month = "feb")

feb_breakdown <- breakdown_function(feb_purchases)

feb_categories <- category_function(feb_purchases, "feb")


```

```{r mar}
# mar Purchases -------------------------------------------------------

mar_purchases <- tribble(
  ~place,            ~amount, ~category,
  "brutus_loan",      350.00, "debt",
  "student_loans",    336.10, "debt",
  "mandrin_garden",    12.69, "restaurant",
  "zupas",             11.33, "restaurant",
  "wendys",             2.47, "restaurant",
  "wal_mart",           45.79, "grocery",
  "tropical_smoothie",  7.77, "restaurant",
  "sams_club",          9.92, "grocery",
  "sams_club",          5.76, "restaurant",
  "amazon",            32.15, "baby",
  "sonic",              3.22, "restaurant",
  "amazon",            16.08, "subscription",
  "mortys_cafe",       27.27, "restaurant",
  "costco",             2.69, "restaurant",
  "costco",            99.20, "grocery",
  "krystal",          116.00, "subscription",
  "dominion",         152.44, "house_essential",
  "hoa",               60.00, "house_essential",
  "rocky_mountain",    37.05, "house_essential",
  "nibley_city",      107.49, "house_essential",
  "allstate",          11.50, "house_essential",
  "quantum_fiber",     75.00, "house_essential",
  "costco",             1.62, "restaurant",
  "mortgage",        3856.79, "house_payment",
  "planet_fitness",    10.70, "subscription",
  "ticket_master",    151.17, "hobby",
  "mortys",            27.27, "restaurant",
  "maverik",           35.17, "gas",
  #"target",            19.79, "misc",
  "target",            14.80, "baby",
  "target",             4.99, "grocery",
  "sams_club",         89.04, "misc", # not sure why this isn't showing up
  "in_n_out",           7.43, "restaurant",
  "homegoods",         92.39, "house_var",
  "columbia",          24.15, "clothes",
  "carters",           77.88, "baby",
  "raising_canes",     21.83, "restaurant",
  "habanero_express",  13.02, "restaurant",
  #"target",           143.35, "misc",
  "target",            41.67, "baby",
  "target",           101.68, "clothes",
  #"target",           -75.93, "misc",
  "target",           -18.00, "baby",
  "target",           -57.93, "misc",
  "tjmaxx",           187.99, "clothes",
  "tjmaxx",           -13.93, "clothes",
  "noodles",            8.93, "restaurant",
  "pei_wei",           21.41, "restaurant",
  "nordstrom_rack",    64.29, "clothes",
  "in_n_out",          12.61, "restaurant",
  "target",            58.84, "baby",
  "quilts_etc",        20.48, "new_baby",
  "old_navy",          89.94, "clothes",
  "target",            28.03, "misc",
  "and_collar",       103.16, "clothes",
  "sams_club",         43.82, "gas",
  "seven_eleven",       4.12, "restaurant",
  "target",            12.84, "misc",
  "davis_pizza",       28.19, "restaurant",
  "sams_club",         29.80, "gas",
  "jamba_juice",       18.70, "restaurant",
  "tjmaxx",           -21.44, "clothes",
  "zurchers",          21.39, "bday",
  "wal_mart",            7.27, "baby",
  "in_n_out",           8.06, "restaurant",
  "target",           -30.89, "misc",
  "sonic",              3.24, "restaurant",
  "corner_bakery",     12.86, "restaurant",
  "carters",           51.51, "baby",
  "carters",          -16.12, "baby",
  "trader_joes",       63.37, "grocery",
  "karl_malone_toyota",  500, "new_car",
  #"target",            55.74, "misc",
  "target",            12.69, "personal",
  "target",            20.00, "clothes",
  "target",            23.05, "grocery",
  "tjmaxx",            64.31, "clothes",
  "adobe",             10.69, "subscription",
  "jimmy_johns",        8.69, "restaurant",
  "davis_park",        94.00, "golf",
  "justin",           -38.00, "golf",
  "gus_da_bus",       -20.00, "golf",
  "twisted_sugar",      6.50, "restaurant",
  "maverik",           41.69, "gas",
  "seven_eleven",       1.07, "restaurant",
  "sonic",              3.24, "restaurant",
  "rr_bbq",            11.95, "restaurant",
  "crown_burgers",     10.81, "restaurant",
  "twirl",             80.38, "clothes",
  "maverik",           26.82, "gas",
  "maverik",            4.12, "restaurant",
  "maverik",            3.21, "restaurant",
  "boba_world",        28.00, "restaurant",
  "quick_quack",       11.99, "misc",
  "maverik",            2.98, "restaurant",
  "seven_eleven",      46.67, "gas",
  "thai_house",        66.00, "restaurant",
  "great_harvest",     12.95, "restaurant",
  "maverik",            4.37, "restaurant",
  "smiths",            24.15, "grocery",
  "maverik",           33.63, "gas",
  "taco_time",         21.93, "restaurant",
  "blacksmith",         7.23, "restaurant",
  "seven_eleven",      40.46, "gas",
  "roku_disney",       15.00, "subscription",
  "apple",              2.99, "subscription",
  "quick_quack",       41.99, "subscription",
  "amazon",            48.24, "baby",
  "apple",             10.99, "subscription",
  "season_tickets",   550.00, "football",

  
  # Breakdown Carolina expenses
  "hotel_char (extra hotel)",       116.56, "vacation_carolina",
  "hotel_char (extra hotel)",        71.02, "vacation_carolina",
  "parking (parking)",            1.50, "vacation_carolina",
  "parking (parking)",            1.62, "vacation_carolina",
  "parking (parking)",            3.00, "vacation_carolina",
  "interval (hotel week)",          79.00, "vacation_carolina",
  "expedia (extra hotel)",           93.24, "vacation_carolina",
  "wal_mart (personal)",           75.69, "vacation_carolina",
  "waffle_house (restaurant)",      21.00, "vacation_carolina",
  "amelies (restaurant)",            8.01, "vacation_carolina",
  "taco_bell (restaurant)",          4.96, "vacation_carolina",
  "mint_museum (souvenir)",       20.11, "vacation_carolina",
  "sd_missouri (misc)",        4.73, "vacation_carolina",
  "harris_teeter (grocery)",     12.13, "vacation_carolina",
  "enat (restaurant)",              15.58, "vacation_carolina",
  "archer_paper (souvenir)",      16.08, "vacation_carolina",
  "papi_queso (restaurant)",        14.30, "vacation_carolina",
  "522_temp_kiosk (parking)",     3.49, "vacation_carolina",
  "target (grocery)",            36.84, "vacation_carolina",
  "sonic (restaurant)",              5.89, "vacation_carolina",
  "simply_southern (restaurant)",   37.09, "vacation_carolina",
  "pepperbox_dough (restaurant)",    8.28, "vacation_carolina",
  "smoothie_king (restaurant)",     13.29, "vacation_carolina",
  "mcdonalds (restaurant)",          5.94, "vacation_carolina",
  "citgo_oil (restaurant)",          2.31, "vacation_carolina",
  "parkreceipts (experience)",       7.30, "vacation_carolina",
  "tsunami_surf_shop (souvenir)", 37.10, "vacation_carolina",
  "blueberrys_grill (restaurant)",  32.00, "vacation_carolina",
  "rosmery_coin (misc)",       5.00, "vacation_carolina",
  "cook_out (restaurant)",          10.92, "vacation_carolina",
  "jersey_mikes (restaurant)",       7.13, "vacation_carolina",
  "roy_and_sids (restaurant)",      29.00, "vacation_carolina",
  "cook_out (restaurant)",           4.45, "vacation_carolina",
  "barnes_noble (experience)",       5.44, "vacation_carolina",
  "sp_shop (souvenir)",           34.86, "vacation_carolina",
  "arrowhead_cc (experience)",      57.00, "vacation_carolina",
  "battleship (experience)",        29.96, "vacation_carolina",
  "copper_penny (restaurant)",      39.00, "vacation_carolina",
  "circle_k (restaurant)",           7.57, "vacation_carolina",
  "circle_k (gas)",          40.91, "vacation_carolina",
  "chick_fila (restaurant)",        15.83, "vacation_carolina",
  "parking (parking)",            8.40, "vacation_carolina",
  "dead_dog_saloon (restaurant)",   43.16, "vacation_carolina",
  "pf_changs (restaurant)",         20.00, "vacation_carolina",
  "exxonmobil (restaurant)",         4.25, "vacation_carolina",
  "brookgreen_gardens (experience)",44.00, "vacation_carolina",
  "crs (experience)",               16.00, "vacation_carolina",
  "myrtlewood_golf (experience)",   43.00, "vacation_carolina",
  "duck_donuts (restaurant)",        8.29, "vacation_carolina",
  "dead_dog_saloon (restaurant)",   34.00, "vacation_carolina",
  "blue_orb_tours (experience)",    74.20, "vacation_carolina",
  "taco_bell (restaurant)",          6.13, "vacation_carolina",
  "sweet_potatoes (restaurant)",    50.00, "vacation_carolina",
  "lake_city_drivein (restaurant)",  3.89, "vacation_carolina",
  "sams_club (personal)",         34.94, "vacation_carolina",
  "comfort_inn (extra hotel)",      187.85, "vacation_carolina",
  "comfort_inn (extra hotel)",      167.15, "vacation_carolina",
  "christmas_mouse (souvenir)",   64.75, "vacation_carolina",
  "bojangles (restaurant)",          9.56, "vacation_carolina",
  "blueberrys_grill (restaurant)",  28.00, "vacation_carolina",
  "whitaker_garage (parking)",   10.00, "vacation_carolina",
  "wileys_bbq (restaurant)",        38.00, "vacation_carolina",
  "sonic (restaurant)",              3.73, "vacation_carolina",
  "savannah_parking (parking)",   3.00, "vacation_carolina",
  "svannah_clothing (souvenir)",  18.18, "vacation_carolina",
  "mcdonalds (restaurant)",          2.24, "vacation_carolina",
  "leopolds_ice_cream (restaurant)",20.01, "vacation_carolina",
  "i_love_savannah (souvenir)",   13.90, "vacation_carolina",
  "tybee_island (parking)",       8.00, "vacation_carolina",
  "parking (parking)",           10.00, "vacation_carolina",
  "spherix_dnr (experience)",       25.68, "vacation_carolina",
  "sticky_fingers (restaurant)",    25.00, "vacation_carolina",
  "circle_k (gas)",          42.14, "vacation_carolina",
  "circle_k (restaurant)",          12.18, "vacation_carolina",
  "vinne_van_gogo (restaurant)",    24.40, "vacation_carolina",
  "dominos (restaurant)",           16.07, "vacation_carolina",
  "days_inn (extra hotel)",          91.25, "vacation_carolina",
  "adam_reimburse (hotel week)",  -500.00, "vacation_carolina",
  "dairy_queen (restaurant)",        7.01, "vacation_carolina"
) %>% 
  mutate(month = "mar")

mar_breakdown <- breakdown_function(mar_purchases)

mar_categories <- category_function(mar_purchases, "mar")


```

```{r apr}
# apr Purchases -------------------------------------------------------

apr_purchases <- tribble(
  ~place,            ~amount, ~category,
  "krystal",          116.00, "subscription",
  "wal_mart",          117.83, "baby",
  "tj_maxx",           73.79, "baby",
  "lees_marketplace",  87.12, "grocery",
  "chipotle",          22.57, "restaurant",
  "maverik",            4.69, "restaurant",
  "great_harvest",      6.75, "restaurant",
  "center_street",     21.52, "restaurant",
  "amazon",            16.08, "subscription",
  "wal_mart",           28.02, "clothes",
  "maverik",           40.92, "gas",
  "sonic",              3.88, "restaurant",
  "whisperwood",       19.29, "grocery",
  "amazon",           120.84, "baby",
  "over_the_moon",     74.00, "new_baby",
  "banbury_donuts",    18.93, "restaurant",
  "wal_mart",           15.47, "baby",
  "wal_mart",           10.66, "baby",
  "sonic",              3.88, "restaurant",
  "roosters",          63.00, "restaurant",
  "maverik",           40.92, "gas",
  "amazon",           148.73, "baby",
  "smiths",           100.20, "grocery",
  "zupas",             28.06, "restaurant",
  "homegoods",        136.90, "new_baby",
  "maverik",            1.59, "restaurant",
  "great_harvest",     12.85, "restaurant",
  "great_harvest",      6.49, "grocery",
  "zao",               22.52, "restaurant",
  "twisted_sugar",      6.70, "restaurant",
  "aggie_ice_cream",   25.86, "church",
  "bountiful_ridge",   21.00, "golf",
  "wal_mart",           36.18, "gas",
  "sonic",              1.61, "restaurant",
  "rovalis",           42.00, "restaurant",
  "in_n_out",           5.89, "restaurant",
  "arbys",              3.55, "restaurant",
  "sunshine_cafe",     36.00, "restaurant",
  "sunshine_cafe",    -20.00, "restaurant",
  "brutus_loan",     5699.73, "debt",
  "hoa",               60.00, "house_essential",
  "dominion",         110.24, "house_essential",
  "adobe",             10.69, "subscription",
  "zupas",             12.72, "restaurant",
  "santorinis",        21.12, "restaurant",
  "blacksmith",        17.97, "restaurant",
  "student_loans",   1178.25, "debt",
  "mortgage",        3856.79, "house_payment",
  "dominion",         110.24, "house_essential",
  "hoa",               60.00, "house_essential",
  #
  "brutus_loan",     2000.71, "debt",
  "planet_fitness",    10.70, "subscription",
  "rocky_mountain",    36.86, "house_essential",
  "nibley_city",      107.49, "house_essential",
  #"costco",           219.21, "misc",
  "costco",            69.99, "baby",
  "costco",            25.00, "clothes",
  "costco",            25.00, "house_var",
  "costco",           100.21, "grocery",
  "quantum_fiber",     75.00, "house_essential",
  "topical_smoothie",   8.31, "restaurant",
  "mandarin_garden",    6.48, "restaurant",
  "great_harvest",      7.10, "grocery",
  "twisted_sugar",      2.97, "restaurant",
  "smiths",            31.12, "grocery",
  "sams_club",         59.48, "grocery",
  "daisy_dog",         73.50, "personal",
  "taco_bell",         12.90, "restaurant",
  "ginnys",             3.72, "restaurant",
  "costa_vida",         9.92, "restaurant",
  "wal_mart",            9.43, "misc",
  "crumbl",             8.46, "restaurant",
  "jacks_wood_fire",   36.98, "restaurant",
  "homegoods",         32.06, "house_var",
  "cafe_rio",          10.49, "restaurant",
  "humanitix",          9.33, "hobby",
  "tj_maxx",           34.21, "baby",
  "zupas",             25.36, "restaurant",
  "delta",             11.20, "vacation_louisville",
  "twisted_sugar",      7.12, "restaurant",
  "wal_mart",           38.18, "gas",
  "trader_joes",       64.35, "grocery",
  "hug_hes",           60.20, "restaurant",
  "hug_hes",            4.86, "grocery",
  "discount_tire",    957.87, "car",
  "sonic",              6.01, "restaurant",
  "roku_disney",       15.01, "subscription",
  "panda_express",     18.58, "restaurant",
  "amazon",             7.73, "grocery",
  "mandarin_garden",    6.48, "restaurant",
  "mcdonalds",          2.78, "restaurant",
  "in_n_out",           7.99, "restaurant",
  "noodles",           17.28, "restaurant",
  "apple",              2.99, "subscription",
  "quick_quack",       41.99, "subscription",
  "chipotle",          25.76, "restaurant",
  "tj_maxx",           13.90, "clothes",
  "old_navy",          26.72, "baby",
  "locals",            34.22, "baby",
  "great_harvest",      9.60, "restaurant",
  "maverik",            2.98, "restaurant",
  "threadwallets",     50.26, "mothers_day",
  "desert_aqua",       65.41, "mothers_day",
  "bath_bodyworks",   105.66, "mothers_day",
  "humanitix",          9.31, "hobby",
  "panda_express",     10.58, "restaurant",
  "usu_parking",        3.00, "hobby",
  "usu_dining",         3.55, "restaurant",
  "maverik",           45.70, "gas",
  "apple",             10.99, "subscription",
  "allstate",          11.50, "subscription",
  "allstate",        1278.29, "car",
  "maverik",           20.71, "gas",
  "maverik",            1.81, "restaurant",
  #"target",           179.98, "misc",
  "target",            24.00, "clothes",
  "target",            40.00, "family",
  "target",             5.00, "grocery",
  "target",           110.98, "baby",
  "sonic",              1.93, "restaurant",
  "amazon",            60.05, "baby",
  "hotel",            595.35, "vacation_louisville",
  "amazon",           289.56, "new_baby",
  "amazon",            27.54, "misc",
  "maverik",           46.03, "gas",
  "claires",           21.48, "personal",
  "spitz",             16.04, "restaurant",
  "trader_joes_bh",    41.56, "grocery",
  "smiths_bh",         40.23, "grocery",
  "sams_club_bh",      50.03, "grocery",
  "quilted_bear_bh",   42.78, "family",
  "great_harvest_bh",  29.03, "grocery",
  "zupas_bh",          11.36, "restaurant",
  "student_loans",    136.10, "debt",
  
  # Breakdown Carolina Vacation
  "krystal (misc)",           50.00, "vacation_carolina",
  "village_juice (restaurant)",     14.02, "vacation_carolina",
  "melo_frog_llc (restaurant)",     20.14, "vacation_carolina",
  "amelies (restaurant)",           17.58, "vacation_carolina",
  "speedway (restaurant)",           9.16, "vacation_carolina",
  "primohoagies (restaurant)",      26.13, "vacation_carolina",
  "exxonmobil (gas)",        36.99, "vacation_carolina",
  "wendys (restaurant)",            12.30, "vacation_carolina",
  "avanti_markets (restaurant)",     5.46, "vacation_carolina",
  "budget_rent_car (rental_car)",  516.05, "vacation_carolina",
  "seven_eleven (gas)",      35.08, "vacation_carolina",
  "maverik (restaurant)",            2.98, "vacation_carolina",
  "cypress_gardens (experience)",   20.00, "vacation_carolina",
) %>% 
  mutate(month = "apr")

apr_breakdown <- breakdown_function(apr_purchases)

apr_categories <- category_function(apr_purchases, "apr")


```

```{r may}
# may Purchases -------------------------------------------------------

may_purchases <- tribble(
  ~place,                 ~amount, ~category,
  "tj_maxx_bh",             28.95, "clothes",
  "noodle_house",           10.82, "restaurant",
  "chinatown",               2.05, "restaurant",
  "santo_taco",             11.41, "restaurant",
  "raising_canes",          13.82, "restaurant",
  "target_bh",              75.52, "family",
  "sonic_bh",                6.47, "restaurant",
  "shake_shack_bh",         13.51, "restaurant",
  "nielsens_bh",             2.70, "restaurant",
  "sams_club_bh",           42.38, "gas",
  "sams_club_bh",           19.44, "restaurant",
  "amazon",                 16.08, "subscription",
  "crown_burgers_bh",       15.13, "restaurant",
  "seven_eleven_bh",         7.05, "restaurant",
  "hotel",                 172.64, "vacation_louisville",
  "delta_hotel",           -28.98, "vacation_louisville",
  "seven_eleven_bh",         7.05, "restaurant",
  "sams_club",              44.85, "baby",
  "zupas",                  14.06, "restaurant",
  "apple_spice",            12.08, "restaurant",
  "seven_eleven",            4.12, "restaurant",
  "slackwater",              6.22, "restaurant",
  "wal_mart",               104.86, "misc",
  "slackwater",             16.00, "restaurant",
  "salon",                 312.41, "mothers_day",
  "panda",                  10.61, "restaurant",
  "mcdonalds_bh",           12.30, "restaurant",
  "einstein_bagel_bh",      13.31, "restaurant",
  "seven_eleven",            6.25, "restaurant",
  "jolly_wool_bh",           6.00, "family",
  "heartfealt_gift",        65.02, "family",
  "great_harvest",           9.18, "restaurant",
  "desert_aqua",            27.76, "mothers_day",
  "valley_view",            17.00, "golf",
  "tys_dyes",               58.85, "brody_bday",
  "smothered",              31.10, "restaurant",
  "good_olive_oil",         40.01, "family",
  "maverik",                37.35, "gas",
  "maverik",                 4.12, "restaurant",
  "keva_juice",             12.90, "restaurant",
  "riverton_bball",          2.00, "restaurant",
  "holiday_market",         71.12, "misc",
  "valley_view",             6.00, "golf",
  "the_royal",              31.00, "restaurant",
  "taco_bell",               8.92, "restaurant",
  "sinclair_oil",            5.70, "restaurant",
  "maverik",                40.47, "gas",
  "los_hermanos",           11.00, "restaurant",
  "harmons",                 8.49, "restaurant",
  "cafe_rio",               11.57, "restaurant",
  #"target",                 43.60, "misc",
  "target",                 15.00, "mothers_day",
  "target",                 28.60, "grocery",
  "flying_j",                7.82, "restaurant",
  "maverik",                45.23, "gas",
  "jamba",                  18.70, "mothers_day",
  "wal_mart",                 3.00, "grocery",
  "wal_mart",                 7.15, "house_var",
  "adobe",                  10.69, "subscription",
  "dominion",               71.82, "house_essential",
  #"costco",                151.33, "misc",
  "costco",                129.99, "personal",
  "costco",                 21.34, "grocery",
  "hoa",                    60.00, "house_essential",
  "mortgage",             3856.79, "house_payment",
  "planet_fitness",         10.70, "subscription",
  "rocky_mountain",         49.52, "house_essential",
  "nibley_city",           107.49, "house_essential",
  "ulta",                   87.73, "personal",
  "smiths",                 84.01, "grocery",
  "sams_club",              97.69, "grocery",
  "adobe",                  10.69, "subscription",
  "karie_anne",              5.82, "restaurant",
  "jersey_mikes",           10.45, "restaurant",
  "turo",                  400.92, "vacation_louisville",
  "valvoline",              83.72, "car",
  "swig",                    7.56, "restaurant",
  "oreilly",                21.39, "car",
  "autozone",               50.27, "car",
  "logans_heroes",           9.26, "restaurant",
  "in_n_out",                5.67, "restaurant",
  "wal_mart",                32.08, "personal",
  "home_depot",             69.51, "house_var",
  "ulta",                   55.00, "personal",
  "ulta",                   22.12, "jessi_wedding",
  "tj_maxx",                32.07, "baby",
  "buckle",                 53.99, "jessi_wedding",
  "karie_anne",              5.88, "restaurant",
  "cafe_rio",               20.92, "restaurant",
  "maverik",                41.40, "gas",
  "in_n_out",                9.67, "restaurant",
  "taggarts_grill",         25.52, "restaurant",
  "flights_from_home",      39.00, "subscription",
  "eagle_mtn",              28.00, "golf",
  "mandarin_garden",        12.69, "restaurant",
  "wal_mart",                81.30, "house_var",
  "red_barn",               20.00, "restaurant",
  "quantum_fiber",          75.00, "house_essential",
  "student_loan",          136.10, "debt",
  "allstate",               11.50, "subscription",
  #"target",                 71.16, "misc",
  "target",                 36.00, "clothes",
  "target",                 35.16, "personal",
  "noodles",                12.50, "restaurant",
  "harmons",                 4.72, "restaurant",
  "chevron",                38.48, "gas",
  "amazon",                 25.73, "misc",
  #"target",                 37.53, "misc",
  "target",                 10.00, "clothes",
  "target",                 25.00, "baby",
  "target",                -16.09, "baby",
  #"amazon",                 35.34, "misc",
  "amazon",                 17.00, "clothes",
  "amazon",                 18.34, "personal",
  "amazon",                 32.88, "baby",
  #"wal_mart",                93.70, "misc",
  "wal_mart",                24.37, "baby",
  "wal_mart",                69.33, "grocery",
  "target",                 30.47, "misc",
  "blacksmith",              9.96, "restaurant",
  "parking",                 3.49, "misc",
  #"wal_mart",                59.68, "misc",
  "wal_mart",                19.00, "baby",
  "wal_mart",                40.68, "grocery",
  "royals_hot_chicken",     23.20, "vacation_louisville",
  "roku",                   15.01, "subscription",
  "lueberry_acai",           9.54, "vacation_louisville",
  "old_spaghetti",          23.00, "vacation_louisville",
  "burker_king",             6.21, "vacation_louisville",
  "blacksmith",             14.83, "restaurant",
  "louisville_airport",      3.18, "vacation_louisville",
  "merles_whiskey",         16.96, "vacation_louisville",
  "river_house",            18.02, "vacation_louisville",
  "nic_normans",            27.88, "vacation_louisville",
  "quick_quack",            41.99, "subscription",
  "slugger_museum",         74.17, "vacation_louisville",
  "getoutpass",            209.90, "family",
  "cincy_hotel",           128.78, "vacation_louisville",
  "derby_museum",           25.44, "vacation_louisville",
  "churchill_downs",        18.00, "vacation_louisville",
  "apple",                   2.99, "subscription",
  "churchill_downs",        25.50, "vacation_louisville",
  "tjmaxx",                 36.63, "vacation_louisville",
  "sonic",                   5.10, "vacation_louisville",
  "skyline_chili",           7.69, "vacation_louisville",
  "puerto_vallarta",        21.66, "vacation_louisville",
  "pearl_st_game_coffee",    6.49, "vacation_louisville",
  "cincinnati_bb",          19.76, "vacation_louisville",
  "wendys",                 11.10, "vacation_louisville",
  "reds_game",              48.00, "vacation_louisville",
  "square",                 12.00, "vacation_louisville",
  "caseys",                  2.77, "vacation_louisville",
  "old_spaghetti",          15.32, "vacation_louisville",
  "white_castle",            8.62, "vacation_louisville",
  "speedway",               11.82, "vacation_louisville",
  "findlay_market",          3.35, "vacation_louisville",
  "louisville_cream",       14.02, "vacation_louisville",
  "em_sourdough",           18.00, "vacation_louisville",
  "courtyard",              53.02, "vacation_louisville",
  "valero",                 34.86, "vacation_louisville",
  "cincinnati_parking",      5.50, "vacation_louisville",
  "sdf_finish",              3.29, "vacation_louisville",
  "amazon",                 34.22, "baby",
  "amazon",                 21.01, "grocery",
  "wal_mart",                35.18, "gas",
  "chilis",                 12.18, "vacation_louisville",
  "apple",                  10.99, "subscription",
  "twisted_sugar",          17.55, "restaurant",
  "maceys",                 28.27, "grocery",
  "amazon",                187.31, "clothes",
  "amazon",                 29.16, "grocery",
  "amazon",                 26.16, "clothes",
  "smiths",                 47.53, "grocery",
  "sams_club",              12.72, "grocery",
  "sams_club",               6.97, "restaurant",
  "wendys",                  1.94, "restaurant",
  "arbys",                   7.05, "restaurant",
  "stacked",                 8.02, "restaurant",
  "recreation_registration",35.00, "hobby",
  "karie_annes",             9.56, "restaurant",
  "wal_mart",                 5.32, "family",
  "wal_mart",                33.84, "gas",
  "home_depot",            129.40, "house_var",
  "sams_club",              39.01, "house_var",
  "logan_heroes",           16.01, "restaurant",
  "arbys",                   6.04, "restaurant",
  "smiths",                 16.23, "grocery",
  "nielsens",                2.70, "restaurant",
  "maverik",                 1.81, "restaurant"
) %>% 
  mutate(month = "may")

may_breakdown <- breakdown_function(may_purchases)

may_categories <- category_function(may_purchases, "may")


```  
  
```{r jun}
# jun Purchases -------------------------------------------------------

jun_purchases <- tribble(
  ~place,            ~amount, ~category,
  "sweet_lakes",        6.00, "restaurant",
  "pyne_farms",         3.00, "restaurant",
  "great_harvest",      2.50, "restaurant",
  "keva_juice",        12.91, "restaurant",
  "volkers_bakery",    10.75, "restaurant",
  "puzzle",            30.03, "maddie_bday",
  "salsa_del_diablo",   9.92, "grocery",
  "pyne_farms",        12.00, "restaurant",
  "maverik",           43.45, "gas",
  "parking",            2.00, "misc",
  "gourmandise",       36.47, "restaurant",
  "maverik",            5.54, "grocery",
  "keva_juice",        12.90, "restaurant",
  "great_harvest",     15.87, "restaurant",
  "beehive_grill",     15.00, "restaurant",
  "karie_annes",        5.88, "restaurant",
  "amazon",            16.08, "subscription",
  "krystal",          116.00, "subscription",
  "amazon",           680.83, "maddie_bday",
  "lees",              29.64, "grocery",
  "jersey_mikes",      19.94, "restaurant",
  "homegoods",         29.00, "house_var",
  "minky_couture",     86.84, "personal",
  #"wal_mart",          129.26, "misc",
  "wal_mart",           48.62, "house_var",
  "wal_mart",           80.64, "baby",
  "papa_murphy",       11.77, "restaurant",
  "maceys",            35.67, "grocery",
  "crumbl",             9.16, "restaurant",
  "great_harvest",     13.49, "restaurant",
  "canyon_springs",    26.00, "vacation_twin_falls",
  "cafe_rio",          24.79, "restaurant",
  "shoshone_falls",     5.00, "vacation_twin_falls",
  "red_robin",         25.00, "vacation_twin_falls",
  "mo_bettahs",        15.54, "vacation_twin_falls",
  "chevron",            5.30, "vacation_twin_falls",
  "chevron",           45.59, "vacation_twin_falls",
  "lowes",            223.63, "maddie_bday",
  "mcdonalds",          3.85, "vacation_twin_falls",
  "maverik",           33.29, "vacation_twin_falls",
  "maverik",           16.14, "vacation_twin_falls",
  "wendys",             6.02, "restaurant",
  "taco_time",         11.89, "restaurant",
  "maverik",            6.06, "restaurant",
  "daisy_dog",         52.10, "personal",
  "slc_golf",          10.00, "golf",
  "fresh_mkt",         21.37, "grocery",
  "wendys",             5.19, "restaurant",
  "wendsy",             3.58, "restaurant",
  "noodles",           12.96, "restaurant",
  "maverik",           32.33, "gas",
  "zupas",             11.36, "restaurant",
  "wasatch_bagel",     19.14, "restaurant",
  "tjmaxx",            13.96, "new_baby",
  "old_navy",          24.15, "new_baby",
  "homegoods",         42.97, "personal",
  "gap",              151.70, "new_baby",
  "davanzas",          15.58, "restaurant",
  "davanzas",           6.86, "restaurant",
  "cold_stone",         6.39, "restaurant",
  "carters",          109.13, "new_baby",
  "zao",               21.54, "restaurant",
  "adobe",             10.69, "subscription",
  "wal_mart",           30.60, "gas",
  "valey_view",        15.00, "golf",
  "burger_stop",       13.83, "restaurant",
  "vv_pro_shop",        3.79, "restaurant",
  "santo_taco",        10.33, "restaurant",
  "sams_club",        103.22, "grocery",
  "sams_club",          9.70, "restaurant",
  "maverik",           37.64, "gas",
  "jesus_nava",         3.00, "restaurant",
  "indefinable",        8.55, "restaurant",
  "brazilian_paradise", 9.78, "restaurant",
  "in_n_out",          11.99, "restaurant",
  "home_depot",       111.74, "maddie_bday",
  "amazon_download",    8.61, "family",
  "etsy",               8.13, "maddie_bday",
  "costco",             9.88, "restaurant",
  "costco",            45.05, "grocery",
  "dominion_energy",   47.87, "house_essential",
  "hoa",               83.00, "house_essential",
  "mortgage",        3856.79, "house_payment",
  "anna_tao",           3.00, "restaurant",
  "beautiful_birth",  620.00, "new_baby",
  "kenzie_stinger",    65.00, "maddie_bday",
  "home_depot",       250.00, "maddie_bday",
  "home_depot",        17.14, "house_var",
  "wal_mart",           26.61, "gas",
  "sonic",              3.23, "restaurant",
  "amazon",            28.95, "bday",
  "maverik",            4.12, "restaurant",
  "wal_mart",            9.21, "maddie_bday",
  "home_depot",        61.72, "maddie_bday",
  "panda_express",     13.56, "restaurant",
  "maverik",           12.43, "restaurant",
  "wendys",             7.30, "restaurant",
  "nielsens",          19.65, "restaurant",
  "jersey_mikes",      18.08, "restaurant",
  "home_depot",        19.23, "maddie_bday",
  "chick_fila",         5.56, "restaurant",
  "live_nation",       40.00, "maddie_bday",
  "live_nation",       67.25, "hobby",
  #"target",           122.09, "misc",
  "target",            22.05, "grocery",
  "target",            12.99, "baby",
  "target",            87.05, "personal",
  "philadelphia_sub",  27.86, "maddie_bday",
  "keva_juice",        25.81, "maddie_bday",
  "diamond_concesisons",7.58, "restaurant",
  "wendys",             4.54, "restaurant",
  "maverik",           36.25, "gas",
  "great_harvest",      5.01, "maddie_bday",
  "cutlers",           38.19, "restaurant",
  "roku",              15.01, "subscription",
  "super_8",          177.12, "fathers_day",
  "wal_mart",           24.66, "gas",
  "wal_mart",           15.87, "personal",
  "snakebite",         69.69, "restaurant",
  "taco_time",          9.07, "restaurant",
  "sams_club",         20.70, "grocery",
  "fast_stop",          6.20, "restaurant",
  "sweet_lake",        34.00, "restaurant",
  "smiths",             6.14, "grocery",
  "salsa_del_diablo",   9.92, "grocery",
  "maverik",           40.54, "gas",
  "apple",              2.99, "subscription",
  "quick_quack",       41.99, "subscription",
  "wal_mart",           25.95, "hobby",
  # BEGIN RECOVERY
  "sams_club",        112.78, "hobby",
  "sams_club",        100.19, "grocery",
  "taco_bell",          4.03, "restaurant",
  "lowes",             78.26, "maddie_bday",
  "lees",              48.96, "grocery",
  "great_harvest",     18.69, "grocery",
  "maverik",            4.04, "restaurant",
  "planet_fitness",    10.70, "subscription",
  "rocky_mountain",    35.77, "house_essential",
  "holiday_market",    11.85, "maddie_bday",
  "nibley_city",      107.49, "house_essential",
  "dollar_tree",        1.34, "maddie_bday",
  "rocks",            750.00, "maddie_bday",
  "quantum_fiber",     75.00, "house_essential",
  "amazon",           -93.28, "clothes",
  "apple",             10.99, "subscription",
  "dominos",           15.10, "restaurant",
  "maverik",            3.08, "restaurant",
  "home_depot",        15.11, "maddie_bday",
  "maverik",           21.55, "gas",
  "maverik",            4.04, "restaurant",
  #"wal_mart",          29.12, "misc",
  "wal_mart",          13.00, "house_var",
  "wal_mart",          26.12, "grocery",
  "home_depot",         4.68, "maddie_bday",
  #"sams_club",         45.38, "misc",
  "sams_club",         13.00, "house_var",
  "sams_club",         32.38, "grocery",
  "lees",              28.16, "grocery",
  "homegoods",        139.09, "becks_kids",
  "chick_fila",         5.56, "restaurant",
  "home_depot",        -7.98, "maddie_bday",
  "in_n_out",          11.45, "restaurant",
  "studen_loan",      136.10, "debt"
) %>% 
  mutate(month = "jun")

jun_breakdown <- breakdown_function(jun_purchases)

jun_categories <- category_function(jun_purchases, "jun")


```    
  
```{r jul}
# jul Purchases -------------------------------------------------------

jul_purchases <- tribble(
  ~place,            ~amount, ~category,
  "smiths",            25.19, "grocery",
  "costco",             9.88, "restaurant",
  "costco",            64.20, "subscription",
  "costco",            41.66, "grocery",
  "allstate",        -810.44, "car",
  "progressive",     1185.00, "car",
  "allstate",        -115.50, "house_essential",
  "logan_river",        9.00, "golf",
  "maverik",           34.99, "gas",
  "harmons",           57.35, "grocery",
  "twisted_sugar",      8.62, "restaurant",
  "sams_club",         50.05, "grocery",
  "maceys",            24.92, "grocery",
  "kyte_baby",         79.55, "new_baby",
  "amazon",            16.08, "subscription",
  "super_chix",        17.26, "restaurant",
  "seven_eleven",       5.11, "restaurant",
  "fizz_n_fryz",       18.65, "restaurant",
  "wal_mart",           35.95, "gas",
  "kneaders",           8.62, "restaurant",
  "great_clips",       26.00, "personal",
  "fizz_n_fryz",        6.46, "restaurant",
  "logan_river",       18.00, "golf",
  "logan_farmers_mkt", 13.00, "grocery",
  # July 6
  "in_n_out",          13.07, "restaurant",
  "kneaders",           8.62, "restaurant",
  "smiths",            67.84, "grocery",
  "sams_club",         54.73, "grocery",
  "sams_club",          0.96, "restaurant",
  "in_n_out",          14.31, "restaurant",
  "great_harvest",      7.10, "grocery",
  "taco_bell",          7.10, "restaurant",
  "twisted_sugar",      5.39, "restaurant",
  "homegoods",         24.59, "house_var",
  "walmart",           29.59, "gas",
  "in_n_out",           8.59, "family",
  "karie_annes",       11.24, "restaurant",
  "costa_vida",        10.79, "restaurant",
  "smiths_ballpark",    9.24, "restaurant",
  "seven_eleven",       3.09, "restaurant",
  "sams_club",         19.24, "house_var",
  "interest",         -89.54, "debt",
  "interest",          -9.89, "debt",
  "chick_fila",        11.82, "restaurant",
  "kyte_baby",        185.15, "new_baby",
  "kyte_baby",         65.31, "new_baby",
  "kyte_baby",         56.73, "new_baby",
  "chick_fila",         5.56, "restaurant",
  "sams_club",          6.97, "restaurant",
  "panda_express",     18.04, "restaurant",
  "maverik",            4.12, "restaurant",
  "adobe",             10.69, "subscription",
  "speedway",          39.36, "gas",
  "salsa_del_diablo",  15.43, "grocery",
  "green_jar",          8.68, "restaurant",
  "walmart",          144.72, "misc",
  "zupas",             14.03, "restaurant",
  "tj_maxx",           45.46, "clothes",
  "maverik",           27.53, "gas",
  "rumbi",             19.41, "restaurant",
  "maverik",           12.20, "restaurant",
  "logan_river",       18.00, "golf",
  "dominion_energy",   22.28, "house_essential",
  "hoa",               83.00, "house_essential",
  "mortgage",        3856.79, "house_payment",
  # July 16
  "planet_fitness",    10.70, "subscription",
  "rocky_mountain",    81.40, "house_essential",
  "nibley_city",      116.94, "house_essential",
  "zipz",              22.61, "restaurant",
  "twisted_sugar",      8.62, "restaurant",
  "jersey_mikes",      20.30, "restaurant",
  "maceys",            22.40, "grocery",
  "kyte_baby",        -65.31, "new_baby",
  "great_harvest",      7.10, "grocery",
  "dominos",           15.10, "restaurant",
  "karie_annes",        8.37, "restaurant",
  "amazon",            90.12, "misc",
  "maceys",            24.76, "grocery",
  "chevron",           36.09, "gas",
  "center_street_gril",28.92, "restaurant",
  "aggie_ice_cream",   13.15, "restaurant",
  "quantum_fiber",     75.00, "house_essential",
  # July 21
  "walmart",           26.23, "gas",
  "sonic",              6.45, "restaurant",
  "roku",              15.01, "subscription",
  "harmons",            9.94, "grocery",
  "marshalls",          8.57, "baby",
  "trader_joes",       28.98, "grocery",
  "sweet_lake",         6.53, "restaurant",
  "noodles",           11.13, "restaurant",
  "chick_fila",         3.62, "restaurant",
  "walmart",           29.53, "personal",
  "lids",              16.12, "clothes",
  "carters",           24.81, "new_baby",
  "quick_quack",       41.99, "subscription",
  "sams_club",         37.45, "gas",
  "openai",            10.70, "hobby",
  "apple",              2.99, "subscription",
  "spitz",             14.61, "restaurant",
  "scheels",           30.03, "clothes",
  "keva_juice",        12.90, "restaurant",
  "maverik",           44.10, "gas",
  "rosehaven",        114.00, "personal",
  "kyte_baby",        -56.73, "new_baby",
  "crumbl",             4.31, "restaurant",
  "chip_cookie",       13.93, "restaurant",
  "taco_bell",          3.11, "restaurant",
  "maceys",            58.29, "grocery",
  "arbys",             16.38, "restaurant",
  "walmart",           92.67, "personal",
  "lebeaus",           33.22, "restaurant",
  "maverik",           40.74, "gas",
  "maceys",            11.32, "grocery",
  "apple",             10.99, "subscription",
  "ulta",              85.61, "personal",
  "sierra",           128.36, "clothes",
  #"sams_club",        147.20, "misc",
  "sams_club",         42.00, "baby",
  "sams_club",         12.98, "clothes",
  "sams_club",         20.00, "house_var",
  "sams_club",         72.22, "grocery",
  "sams_club",          5.76, "restaurant",
  "le_croissant",       5.00, "restaurant",
  "great_harvest",      6.75, "grocery",
  "brazilian_paradise", 9.78, "restaurant",
  "in_n_out",          15.01, "restaurant",
  "smiths",            27.02, "grocery",
  "progressive",       13.00, "misc",
  "costco",             4.84, "restaurant",
  "costco",            17.49, "grocery",
  "student_loan",     136.10, "debt",
  "venmo_dresser",    350.00, "new_baby",
  "jimmy_johns",        9.00, "restaurant",
  "krystal",          116.00, "subscription",
  "krystal",          116.00, "subscription",
  "costco",             2.90, "restaurant",
  # July 29 
  "twisted_sugar",     11.97, "restaurant",
  "tj_maxx",           36.61, "misc",
  "walmart",           63.03, "misc",
  "old_navy",          81.27, "misc",
  "locals",            17.11, "misc",
  "chick_fila",        17.38, "restaurant",
  "walmart",           25.94, "gas",
  "pro_image_sport",   32.16, "new_baby",
  "slc_golf",          18.00, "golf",
  "mcdonalds",          2.18, "restaurant",
  "walmart",          -18.13, "misc",
  "amazon",           -16.82, "misc"
) %>% 
  mutate(month = "jul")

jul_breakdown <- breakdown_function(jul_purchases)

jul_categories <- category_function(jul_purchases, "jul")


```  
  
```{r aug}
# aug Purchases -------------------------------------------------------

aug_purchases <- tribble(
  ~place,            ~amount, ~category,
  "ross",              25.65, "new_baby",
  "mountain_donut",    18.66, "restaurant",
  "walmart",           35.82, "gas",
  "pretty_bird",       37.51, "restaurant",
  "mcdonalds",          2.27, "restaurant",
  "costa_vida",        19.20, "restaurant",
  #"amazon",            93.08, "misc",
  "amazon",            93.08, "new_baby",
  "sams_club",         84.75, "grocery",
  "sams_club",          6.97, "restaurant",
  "maverik",            4.04, "restaurant",
  "maceys",            70.87, "grocery",
  "zipz",              31.61, "restaurant",
  "expositions_foods",  8.66, "restaurant",
  "amazon",            16.08, "subscription",
  "maverik",            4.04, "restaurant",
  "in_n_out",          11.45, "restaurant",
  #"amazon",             7.48, "misc",
  "amazon",             7.48, "new_baby",
  "tropical_smoothie",  8.41, "restaurant",
  "mo_bettahs",        10.09, "restaurant",
  "walmart",           44.49, "house_var",
  "maverik",            4.04, "restaurant",
  "homegoods",         48.12, "house_var",
  "great_harvest",     12.80, "restaurant",
  "taco_bell",         10.53, "restaurant",
  "in_n_out",          19.87, "restaurant",
  #"walmart",          116.15, "misc",
  "walmart",           66.00, "new_baby",
  "walmart",           50.15, "personal",
  "walmart",            1.30, "misc",
  "costco",            44.75, "grocery",
  # August 8
  "walmart",            0.30, "misc",
  "walmart",           35.80, "gas",
  "merchant_charge",    5.89, "misc",
  "great_harvest",      8.80, "grocery",
  "amazon",            10.71, "new_baby",
  "amazon",             8.54, "new_baby",
  "nomys_antojitos",   12.00, "restaurant",
  "maverik",           42.07, "gas",
  #"target",            32.72, "misc",
  "target",             7.70, "baby",
  "target",            25.02, "personal",
  "amazon",            35.37, "hobby",
  "amazon",            21.44, "clothes",
  "amazon",            13.83, "new_baby",
  "catering",           2.16, "restaurant",
  "seatgeek",          41.72, "hobby",
  "salsa_del_diablo",   8.82, "restaurant",
  "pyne_farms",        12.00, "restaurant",
  "venues",            21.55, "hobby",
  "target",            22.69, "anniversary",
  "ruths_diner",       53.00, "anniversary",
  "nielsens",           5.39, "anniversary",
  "keva_juice",        12.90, "anniversary",
  "cinemark",          17.70, "anniversary",
  "priceline",        284.84, "anniversary",
  "maverik",           29.57, "anniversary",
  "maverik",            2.03, "anniversary",
  "cinemark",           9.12, "anniversary",
  "trader_joes",       55.24, "grocery",
  "street_tacos",      13.01, "anniversary",
  "maverik",            4.12, "anniversary",
  "adobe",             10.69, "subscription",
  #"sams_club",        129.53, "misc",
  "sams_club",         62.00, "baby",
  "sams_club",         67.53, "grocery",
  "sams_club",          4.83, "restaurant",
  "amex_renwal",      150.00, "misc",
  "interest",         -77.78, "debt",
  "interest",         -37.49, "debt",
  "chick_fila",         8.75, "restaurant",
  "tropical_smoothie",  9.67, "restaurant",
  "amazon",           -16.08, "hobby",
  "amazon",           -19.19, "hobby",
  "walmart",           33.48, "gas",
  "maverik",            4.12, "restaurant",
  "jump_zone",          6.42, "hobby",
  "sabores",           29.69, "restaurant",
  "maceys",            10.07, "grocery",
  "maceys",             3.59, "restaurant",
  "thai_house",        27.97, "restaurant",
  "sams_club",          3.05, "restaurant",
  "chick_fila",         4.31, "restaurant",
  "walmart",           19.20, "football",
  "walmart",           36.50, "gas",
  "twisted_sugar",     11.07, "restaurant",
  "topical_smoothie",   8.41, "restaurant",
  "raising_canes",     15.67, "restaurant",
  "maceys",             1.38, "restaurant",
  "maceys",            26.18, "grocery",
  "dominos",           15.10, "restaurant",
  "wendys",             3.97, "restaurant",
  "sams_club",         37.21, "misc",
  "lees_marketplace",  45.80, "grocery",
  "amazon",            16.04, "misc",
  "maverik",           27.62, "gas",
  "maverik",            5.95, "restaurant",
  #"walmart",           36.43, "misc",
  "walmart",            7.94, "baby",
  "walmart",           28.49, "personal",
  "beehive_grill",     47.00, "restaurant",
  "walmart",          231.09, "misc",
  "gossner",           31.01, "restaurant",
  "christmas_mouse",   21.94, "vacation",
  "roku",              15.01, "subscription",
  "panda_express",     18.04, "restaurant",
  "karie_annes",        7.56, "restaurant",
  "wendys",             7.95, "restaurant",
  "apple",             12.85, "subscription",
  "walmart",           44.49, "misc",
  "quick_quack",       41.49, "subscription",
  "noodles",            8.21, "restaurant",
  "logan_hospital",     6.66, "restaurant",
  "apple",              2.99, "subscription",
  "rubys_pizza",       26.97, "restaurant",
  "roku",              10.66, "subscription",
  "jdawgs",            10.80, "restaurant",
  "krispy_kreme",      15.60, "restaurant",
  "walmart",           17.00, "grocery",
  "taco_bell",         12.68, "restaurant",
  "walmart",           37.35, "clothes",
  "sams_club",         74.26, "grocery",
  "maceys",            22.85, "grocery",
  "maceys",             9.24, "grocery",
  "maceys",             1.02, "grocery",
  "zupas",             14.03, "restaurant",
  "taco_time",         13.54, "restaurant",
  "apple",             10.99, "subscription",
  "barkers_propane",   19.26, "house_var",
  "maverik",            4.04, "restaurant",
  "maceys",             3.08, "grocery",
  "walmart",           13.70, "personal",
  "valvoline",        310.28, "car",
  "smoked_taco",       26.14, "restaurant",
  "blacksmith",        12.67, "restaurant",
  "staiton_park",      19.29, "baby",
  "breakfast_truck",    5.35, "restaurant",
  "jesus_nava",         6.00, "restaurant",
  "tj_maxx",           29.94, "baby",
  "dominion",          22.61, "house_essential",
  "hoa",               83.00, "house_essential",
  "mortgage",        3856.79, "house_payment",
  "rocky_mountain",   173.68, "house_essential",
  "planet_fitness",    10.70, "subscription",
  "nibley_city",      124.29, "house_essential",
  "student_loan",     136.10, "debt",
  "hyrum_auto",       486.32, "car"
) %>% 
  mutate(month = "aug")

aug_breakdown <- breakdown_function(aug_purchases)

aug_categories <- category_function(aug_purchases, "aug")


```  

```{r sep}
# sep Purchases -------------------------------------------------------

sep_purchases <- tribble(
  ~place,            ~amount, ~category,
  "walmart",           35.60, "gas",
  "smiths",            21.77, "grocery",
  "sams_club",         38.86, "grocery",
  "sams_club",          6.97, "restaurant",
  "old_navy",          22.46, "baby",
  "great_clips",       26.00, "personal",
  "einstein_bros",     13.49, "restaurant",
  "delta",             11.20, "vacation_cali",
  "costa_vida",        10.79, "restaurant",
  "jamba_juice",        7.77, "restaurant",
  "fantasy_football",  83.99, "hobby",
  "twisted_sugar",      8.62, "restaurant",
  "great_harvest",      6.75, "grocery",
  "gossner",           10.30, "grocery",
  "amazon",            16.08, "subscription",
  "logans_heroes",     17.85, "restaurant",
  "walmart",           17.59, "personal",
  "walmart",           21.88, "gas",
  "vioc_gt0022",      104.18, "car",
  "dmv_renewal",      151.25, "car",
  "twisted_sugar",      8.58, "restaurant",
  "in_n_out",           3.40, "restaurant",
  "maceys",            20.71, "grocery",
  "arbys",             15.66, "restaurant",
  "sonic",              8.60, "restaurant",
  "maverik",           38.43, "gas",
  "jody_memmott",      15.71, "restaurant",
  "cc_candies",         5.93, "restaurant",
  "utah_stadium",      14.00, "restaurant",
  #"walmart",           63.61, "misc",
  "walmart",           34.11, "personal",
  "walmart",           29.50, "house_var",
  "walmart",            6.30, "grocery",
  "taco_bell",          7.30, "restaurant",
  "maverik",           10.28, "restaurant",
  "taco_bell",          8.62, "restaurant",
  "maverik",           40.41, "gas",
  "logan_166",         14.03, "misc",
  "maverik",            0.95, "restaurant",
  "target",           198.38, "new_baby",
  "sonic",              6.47, "restaurant",
  "slackwater",        48.00, "restaurant",
  "vintage_market",    18.66, "hobby",
  "interest",        -113.47, "debt",
  "light_room",        10.69, "subscription",
  "maverik",           57.01, "gas", 
  "maverik",           35.96, "gas", 
  "maverik",            5.15, "restaurant",
  "utah_state_tik",   180.45, "football",
  "sams_club",         68.00, "grocery",
  "maceys",            30.53, "grocery",
  "great_harvest",     13.65, "restaurant",
  # Sept 16
  "walmart",           27.84, "gas",
  "sonic",              7.53, "restaurant",
  "slc_golf",          64.00, "golf",
  "lemus_farms",       18.54, "grocery",
  "eggs_in_city",      15.38, "restaurant",
  "davis_park",        48.00, "golf",
  "wendys",             9.71, "restaurant",
  "tiwsted_sugar",      4.31, "restaurant",
  "maverik",           23.53, "gas",
  "wasatch_bagel",      8.02, "restaurant",
  "pike_peak_lemon",   23.03, "restaurant",
  "heartfealt_gifts",  27.09, "misc",
  "desert_aqua",       64.05, "house_var",
  "juniper",           31.35, "restaurant",
  "bliss",             68.00, "clothes",
  "sugar_mamas",        8.58, "restaurant",
  "pike_peak_lemon",   12.96, "restaurant",
  "mcdonalds",          3.22, "restaurant",
  "jolly_wool",         6.00, "clothes",
  "chevron",           39.46, "gas",
  #"walmart",           69.54, "misc",
  "walmart",           31.20, "grocery",
  "walmart",           38.34, "baby",
  "herms",             16.00, "restaurant",
  "roku_disney",       26.81, "subscription",
  "locals",            14.84, "new_baby",
  "jersey_mikes",      20.20, "restaurant",
  "lagoon",            20.00, "hobby",
  "lagoon_dd",          4.00, "restaurant",
  "taco_bell",          7.32, "restaurant",
  "walmart",           39.22, "gas",
  "vital_records",     27.39, "misc",
  "sabores",           31.29, "restaurant",
  "mo_bettahs",         6.44, "restaurant",
  "apple",              2.99, "subscription",
  "trader_joes",       46.22, "grocery",
  "target",           145.69, "baby",
  "sonic",              3.23, "restaurant",
  "sams_club",         49.73, "grocery",
  "sams_club",          2.71, "restaurant",
  "karie_annes",       10.26, "restaurant",
  "walmart",           27.84, "gas",
  "gusher_pizza",      49.00, "vacation_yellowstone3",
  "chevron",            3.74, "vacation_yellowstone3",
  "super_save",        51.14, "vacation_yellowstone3",
  "super_save",         9.74, "vacation_yellowstone3",
  "mammoth",           12.52, "vacation_yellowstone3",
  "mammoth",            6.26, "vacation_yellowstone3",
  "apple",             10.99, "subscription",
  "super_save",         6.99, "vacation_yellowstone3",
  "super_save",         5.25, "vacation_yellowstone3",
  "smith_chandler",    54.06, "vacation_yellowstone3",
  "bear_country",      10.13, "vacation_yellowstone3",
  "apple",              7.50, "subscription",
  "dairy_queen",       15.02, "vacation_yellowstone3",
  "mcdonalds",          7.76, "restaurant",
  "maverik",           54.82, "vacation_yellowstone3",
  "walmart",           46.83, "misc",
  "kid_to_kid",        33.65, "baby",
  "judges",            12.00, "misc",
  "in_n_out",           5.72, "restaurant",
  "homegoods",         36.34, "misc",
  "great_harvest",      9.60, "grocery",
  "gossner_foods",     16.38, "grocery",
  "big_deal_outlet",   11.20, "clothes",
  "bath_body_works",   37.40, "house_var",
  "smiths",            29.37, "grocery",
  "planet_fitness",    52.43, "subscription",
  "dominion_energy",   18.88, "house_essential",
  "winco_foods",       18.96, "grocery",
  "costco",             7.19, "restaurant",
  "costco",           116.93, "grocery",
  "hoa",               83.00, "house_essential",
  "usu_office",        16.50, "football",
  "mortgage",        3856.79, "house_payment",
  "trader_joes",       34.20, "grocery",
  "planet_fitness",    10.70, "subscription",
  "nibley_city",      129.54, "house_essential",
  "rocky_mountain",   161.92, "house_essential",
  "super_chix",        17.26, "restaurant",
  "student_loan",     136.10, "debt",
  "krystal",          232.00, "subscription",
  "nate",             181.34, "vacation_gus"
) %>% 
  mutate(month = "sep")

sep_breakdown <- breakdown_function(sep_purchases)

sep_categories <- category_function(sep_purchases, "sep")


```  

```{r oct}
# oct Purchases -------------------------------------------------------

oct_purchases <- tribble(
  ~place,            ~amount, ~category,
  "costco",             7.19, "restaurant",
  "costco",            63.41, "grocery",
  "dominion_energy",   21.45, "house_essential",
  "ridgeline_park",    83.00, "house_essential",
  "costco",             0.75, "restaurant",
  "costco",            80.54, "baby_blessing",
  "mortgage",        3856.79, "house_payment",
  "rocky_mountain",   124.10, "house_essential",
  "planet_fitness",    10.70, "subscription",
  "nibley_city",      119.04, "house_essential",
  "elana",             16.00, "vacation_gus",
  "justin",            87.28, "vacation_gus",
  "elana",             77.89, "vacation_gus",
  "amy",                8.00, "restaurant",
  "krystal",          100.00, "baby",
  "zurchers",          34.05, "halloween",
  "tj_maxx",          695.48, "car_accident",
  "jersey_mikes",      18.25, "restaurant",
  "hobby_lobby",       73.86, "halloween",
  "panda_express",     18.58, "restaurant",
  "cold_stone",        23.49, "restaurant",
  "chilis",             6.79, "restaurant",
  "walmart",           55.47, "gas",
  "minimart",           7.09, "restaurant",
  "maverik",            2.03, "restaurant",
  "maverik",            2.03, "restaurant",
  "seven_eleven",       6.19, "restaurant",
  "taco_stand",         9.25, "vacation_gus",
  "tropical_smoothie",  7.98, "restaurant",
  "great_harvest",     10.44, "grocery",
  "amazon_prime",      16.08, "subscription",
  "walmart",           37.52, "misc",
  "nothing_bundt",     41.53, "restaurant",
  "maceys",            17.27, "grocery",
  "chipotle",          22.14, "restaurant",
  "wendys",            15.09, "restaurant",
  "dominos",           32.36, "restaurant",
  "amazon",           171.19, "misc",
  "carters",           96.72, "new_baby",
  "kyte_baby",          7.50, "new_baby",
  "maverik",           42.06, "gas",
  "hug_hes",           13.78, "restaurant",
  "cross_e_ranch",     29.92, "hobby",
  "walmart",            7.16, "baby_blessing",
  "jesus_nava",         3.00, "restaurant",
  "black_island",      27.00, "hobby",
  "taco_bell",          4.19, "restaurant",
  "costa_vida",        26.43, "restaurant",
  "interest",         -92.89, "debt",
  "raising_canes",    158.75, "baby_blessing",
  "photoshop",         10.69, "subscription",
  "sams_club",         55.52, "gas",
  "sams_club",         74.17, "misc",
  "lees",              84.74, "grocery",
  "mcdonalds",          6.14, "restaurant",
  "amazon",            24.14, "misc",
  "super_chix",        25.89, "restaurant",
  "taco_time",         13.79, "restaurant",
  "daisy_dog",         48.89, "personal",
  "spilled_milk",       8.16, "restaurant",
  "zupas",             14.03, "restaurant",
  "dmv",                6.00, "car",
  "papa_murphy",       19.24, "restaurant",
  "walmart",           40.14, "misc",
  "target",           -68.64, "misc",
  "michaels",          53.51, "halloween",
  "hobby_lobby",       49.74, "halloween",
  "habit_burger",      27.03, "restaurant",
  "walmart",           40.14, "misc",
  "pei_wei",           27.57, "restaurant",
  "nordstrom_rack",    24.64, "clothes",
  "utah_stadium",      15.75, "restaurant",
  "zurchers",          39.97, "halloween",
  "zurchers",          20.24, "halloween",
  "trader_joes",       41.45, "grocery",
  "tj_maxx",           56.80, "clothes",
  "buckle",           229.07, "clothes",
  "amazon",            11.97, "misc",
  "amazon",            10.15, "misc",
  "amazon",             8.23, "misc",
  "ulta",              53.63, "personal",
  "tj_maxx",           50.38, "baby",
  "sierra",            16.08, "clothes",
  "jamba_juice",       15.14, "restaurant",
  "maverik",           38.10, "gas",
  "roku",              28.97, "subscription",
  "old_navy",          13.91, "baby",
  "locals",            84.51, "baby",
  "quick_quack",       12.99, "subscription",
  "ross",              29.94, "clothes",
  "sierra",            10.69, "clothes",
  "chick_fila",         8.25, "restaurant",
  "amazon",            21.44, "misc",
  "amazon",            41.80, "misc",
  "walmart",           57.71, "misc",
  "starbucks",         10.61, "restaurant",
  #"walmart",           58.34, "misc",
  "walmart",           15.09, "grocery",
  "walmart",           43.25, "baby",
  "lees",              65.44, "grocery",
  "lees",               3.08, "grocery",
  "in_n_out",          19.28, "restaurant",
  "apple",              2.99, "subscription",
  "chilis",            11.87, "restaurant",
  "walmart",           23.08, "misc",
  "sams_club",         57.66, "misc",
  "sams_club",          6.97, "restaurant",
  "walmart",           18.96, "misc",
  "walmart",           38.19, "misc",
  "tj_maxx",           78.38, "halloween",
  "target",            24.20, "halloween",
  "old_navy",          27.71, "halloween",
  "michaels",          18.74, "halloween",
  "apple",             10.99, "subscription",
  "walmart",           11.38, "halloween",
  "taco_bell",         16.99, "restaurant",
  "apple",             12.85, "subscription",
  "amazon",            53.45, "misc",
  "sams_club",         77.97, "misc",
  "sams_club",          3.63, "restaurant",
  "chic_fila",         15.00, "restaurant",
  "ae_direct",         56.54, "misc",
  "walmart",           15.82, "halloween",
  "maverik",           40.20, "gas",
  "walmart",            2.96, "halloween",
  "maceys",             9.02, "grocery",
  "student_loan",     136.10, "debt"
) %>% 
  mutate(month = "oct")

oct_breakdown <- breakdown_function(oct_purchases)

oct_categories <- category_function(oct_purchases, "oct")

```  

```{r nov}
# nov Purchases -------------------------------------------------------

nov_purchases <- tribble(
  ~place,            ~amount, ~category,
  "taco_bell",         12.26, "restaurant",
  "tj_maxx",           28.99, "clothes",
  "attn_cca",           6.57, "misc",
  "walmart",           33.27, "gas",
  "minky_couture",     27.49, "chirstmas",
  "maverik",            5.13, "restaurant",
  "maverik",           25.47, "gas",
  "bowmans",            1.53, "restaurant",
  "trader_joes",       74.92, "grocery",
  "amazon",            16.08, "subscription",
  "costa_vida",        19.42, "restaurant",
  "dominos",           30.20, "restaurant",
  "smiths",            69.20, "grocery",
  "jersey_mikes",      18.25, "restaurant",
  "tj_maxx",           80.20, "misc",
  "twisted_sugar",     13.01, "restaurant",
  "tj_maxx",          -48.13, "clothes",
  "tj_maxx",          -28.99, "clothes",
  "home_depot",        38.93, "house_var",
  "homegoods",         50.26, "house_var",
  "airbnb",          1082.06, "vacation_park_city_mckenzie",
  "twisted_sugar",      7.51, "restaurant",
  "maverik",            4.12, "restaurant",
  "chilis",            38.93, "restaurant",
  "lowes",              2.97, "house_var",
  "chick_fila",        10.69, "restaurant",
  "simple_treasures", 208.64, "chirstmas",
  "seven_eleven",      47.80, "gas",
  "caputos",           13.58, "restaurant",
  "walmart",           73.21, "misc",
  "homegoods",         54.00, "misc",
  "amazon",           217.56, "misc",
  "mcdonalds",          6.47, "restaurant",
  "maceys",            22.95, "grocery",
  "maverik",            5.15, "restaurant",
  "homegoods",        107.00, "misc",
  "interest",          22.33, "debt",
  "zao",               12.10, "restaurant",
  "amazon",            19.74, "misc",
  "walmart",           35.72, "misc",
  "adobe",             10.69, "subscription",
  "jimmy_johns",        8.65, "restaurant",
  "maverik",            3.63, "restaurant",
  "trader_joes",      113.75, "grocery",
  "mcdonalds",         11.11, "restaurant",
  "maverik",           43.75, "gas",
  "trader_joes",       16.23, "grocery",
  "zupas",             36.15, "restaurant",
  "walmart",            9.60, "maddie_christmas",
  "walmart",            3.79, "grocery",
  "maceys",            14.39, "grocery",
  "maceys",            16.85, "grocery",
  "maverik",            5.15, "restaurant",
  "lmh_success",       20.46, "misc",
  "sams_club",         27.34, "misc",
  "sams_club",          3.64, "restaurant",
  "cinemark",          33.82, "thanksgiving",
  "bibs_denmark",      63.28, "baby",
  "kneaders",          32.74, "thanksgiving",
  "maverik",            5.42, "restaurant",
  "maceys",            28.59, "thanksgiving",
  "maceys",             8.23, "thanksgiving",
  "nibley",           123.24, "house_essential",
  "planet_fitness",    10.70, "subscription",
  "costco",             1.62, "restaurant",
  "mortgage",        3856.79, "house_payment",
  "rocky_mtn",         78.37, "house_essential",
  "hoa",               83.00, "house_essential",
  "in_n_out",           8.06, "restaurant",
  "dominion",          21.47, "house_essential",
  "maceys",             9.02, "grocery",
  "airbnb",          -725.00, "vacation_park_city_mckenzie",
  "krystal",          116.00, "subscription",
  "krystal",          180.00, "baby",
  "center_strt_pizza", 27.00, "restaurant",
  "bath_and_body",     16.85, "christmas_friends",
  "homegoods",         46.48, "christmas_friends",
  "maceys",            10.29, "grocery",
  "maceys",            27.93, "grocery",
  "roku_disney",       28.97, "subscription",
  "mandarin_garden",   12.69, "restaurant",
  "dicks",              7.22, "misc",
  "maverik",           32.67, "gas",
  "walmart",           97.23, "maddie_christmas",
  "amazon",           115.58, "misc",
  "apple",              2.99, "subscription",
  "logan_166",         14.03, "misc",
  "mcdonalds",          2.81, "restaurant",
  "judges",            69.00, "subscription",
  "sams_club",        146.43, "misc",
  "sams_club",         33.99, "gas",
  "tj_maxx",           27.79, "misc",
  "tj_maxx",           32.09, "misc",
  "utah_concessions",  10.00, "restaurant",
  "in_n_out",          19.28, "restaurant",
  "maceys",            62.93, "grocery",
  "walmart",          177.44, "family_christmas",
  "maverik",            4.12, "restaurant",
  "apple",             10.99, "subscription",
  "taco_bell",         19.46, "restaurant",
  "walmart",           25.59, "gas",
  "great_clips",       25.00, "personal",
  "apple",              7.50, "subscription",
  "chick_fila",        28.79, "restaurant",
  "twisted_sugar",      2.08, "restaurant",
  "ae_retail_west",    78.37, "clothes",
  "altard_state",      84.73, "clothes",
  "amazon",            32.36, "misc",
  "amazon",            32.70, "misc",
  "free_people",       21.45, "maddie_christmas",
  "scheels",           26.80, "maddie_christmas",
  "cinemark",          24.90, "hobby",
  "fp_kids",          122.45, "baby",
  "lagoon",           658.12, "christmas",
  "fp_py_hdos",        12.51, "baby",
  "urban_outfiters",   24.50, "clothes",
  "walmart",           35.18, "personal",
  "zara",              21.21, "baby",
  "amazon",            53.36, "misc",
  "amazon",            14.52, "misc",
  "dominos",           42.39, "mckenzie_bday",
  "hobby_lobby",       17.17, "mckenzie_bday",
  "jersey_mikes",      14.09, "restaurant",
  "zurchers",          74.25, "mckenzie_bday",
  "nothing_bundt_cake", 41.20, "mckenzie_bday",
  "sams_club",           4.83, "restaurant",
  "student_loan",      136.10, "debt",
  "car_payment",       507.00, "debt"
) %>% 
  mutate(month = "nov")

nov_breakdown <- breakdown_function(nov_purchases)

nov_categories <- category_function(nov_purchases, "nov")

```  

```{r dec}
# dec Purchases -------------------------------------------------------

dec_purchases <- tribble(
  ~place,            ~amount, ~category,
  "trader_joes",      162.80, "grocery",
  "sams_club",         41.75, "gas",
  "tonies",            57.76, "josie_christmas",
  "tubby_todd",        70.19, "new_baby",
  #"sams_club",        110.23, "misc",
  "sams_club",         55.25, "baby",
  "sams_club",         54.98, "new_baby",
  "walmart",           82.53, "misc",
  "amazon",            96.29, "misc",
  "bose",             212.93, "maddie_christmas",
  "crown_burger",      25.19, "restaurant",
  "gym_shark",         35.82, "clothes",
  "amazon_prime",      16.08, "subscription",
  "bose",              36.38, "misc",
  "twisted_sugar",      7.02, "restaurant",
  "san_diablo",        12.00, "vacation_park_city_mckenzie",
  "tock_cafe",         46.00, "vacation_park_city_mckenzie",
  "cutie_cles",        42.00, "hobby",
  "sushi_monster",     32.00, "vacation_park_city_mckenzie",
  "verizon",           71.85, "maddie_phone",
  "amazon",            38.20, "misc",
  "davanzas",          26.39, "vacation_park_city_mckenzie",
  "sock_city",         48.96, "maddie_christmas",
  "rocky_mountain",     9.63, "vacation_park_city_mckenzie",
  "cafe_galleria",     55.44, "vacation_park_city_mckenzie",
  "carters",           36.53, "baby",
  "gap_outlet",        74.63, "baby",
  "old_navy",          47.04, "baby",
  "shirt_off",         27.21, "vacation_park_city_mckenzie",
  "smiths",            10.89, "vacation_park_city_mckenzie",
  "tj_maxx",           27.92, "baby",
  "atticus_coffee",    16.78, "vacation_park_city_mckenzie",
  "exxon_mobil",       46.06, "gas",
  "shirt_off",         27.21, "vacation_park_city_mckenzie",
  "sock_city",        155.40, "family_christmas",
  "pack_city",         16.90, "vacation_park_city_mckenzie", #ornament
  "snapfish",          15.55, "misc",
  "wasatch_bagel",      8.02, "vacation_park_city_mckenzie",
  "maceys",            34.47, "grocery",
  "sams_club",         51.50, "grocery",
  "salad_spot",        10.69, "restaurant",
  "locals",            53.46, "christmas",
  "old_navy",          33.36, "baby",
  "nothing_bundt",     31.95, "dalton_bday",
  "walmart",          112.99, "misc",
  "maceys",             5.76, "dalton_bday",
  "tacos_el_robert",    9.98, "restaurant",
  "costa_vida",        14.56, "restaurant",
  "maverik",           35.81, "gas",
  "walmart",            1.03, "hobby",
  "rosie",             31.87, "misc",
  "adobe",             10.69, "subscription",
  "sams_club",        124.74, "misc",
  "zao",                2.11, "restaurant",
  "walmart",           21.34, "house_var",
  "gourmandise",       59.64, "mom_bday",
  "mandarin_garden",   12.69, "restaurant",
  #"walmart",           20.13, "misc",
  "walmart",            3.98, "grocery",
  "walmart",           16.15, "house_var",
  #"sams_club",         94.96, "misc"
  "sams_club",         34.86, "bannack_christmas",
  "sams_club",         60.10, "new_baby",
  "costco",             2.90, "restaurant",
  "sams_club",          4.83, "restaurant",
  "dominion_energy",   48.71, "house_essential",
  "hoa",               83.00, "house_essential",
  "costco",             2.15, "restaurant",
  "mortgage",        3856.79, "house_payment"
) %>% 
  mutate(month = "dec")

dec_breakdown <- breakdown_function(dec_purchases)

dec_categories <- category_function(dec_purchases, "dec")

``` 

<!-- Data Preparation -->
  
```{r Yearly Aggregate Data Prep}

# Aggregate Data

all_months_stacked <- jan_purchases %>% 
  bind_rows(feb_purchases) %>% 
  bind_rows(mar_purchases) %>% 
  bind_rows(apr_purchases) %>% 
  bind_rows(may_purchases) %>% 
  bind_rows(jun_purchases) %>% 
  bind_rows(jul_purchases) %>% 
  bind_rows(aug_purchases) %>%
  bind_rows(sep_purchases) %>% 
  bind_rows(oct_purchases) %>% 
  bind_rows(nov_purchases) %>% 
  bind_rows(dec_purchases) %>% 
  mutate(
    place = case_when(place == "wal_mart" ~ "wal_mart",
                      TRUE ~ place)
  )

wrap_up_categories <- tribble(
  ~current_category        , ~new_category,
  "valentines"             , "holidays",
  "brody_bday"             , "holidays",
  "maddie_bday"            , "holidays",
  "halloween"              , "holidays",
  "mothers_day"            , "holidays",
  "thanksgiving"           , "holidays",
  "christmas"              , "holidays",
  "anniversary"            , "holidays",
  "black_friday"           , "holidays",
  "mom_bday"               , "holidays",
  "jessi_bday"             , "holidays",
  "josie_bday"             , "holidays",   
  "bday"                   , "holidays",  
  "fathers_day"            , "holidays",
  "mckenzie_bday"          , "holidays",
  "maddie_christmas"       , "holidays",
  "christmas_friends"      , "holidays",
  "family_christmas"       , "holidays",
  "photography"            , "hobby",
  "football"               , "hobby",
  "golf"                   , "hobby",
  "barbie_party"           , "hobby",
  "bunco"                  , "hobby",
  "snowboarding"           , "hobby",
  "hiking"                 , "hobby",
  "jessi_wedding"          , "hobby",
  "vacation"               , "vacations",
  "vacation_branson"       , "vacations",
  "vacation_cali"          , "vacations", 
  "vacation_moab"          , "vacations", 
  "vacation_park_city"     , "vacations",         
  "vacation_st_george"     , "vacations",         
  "vacation_waco"          , "vacations",    
  "vacation_yellowstone"   , "vacations", 
  "yellowstone_vacation2"  , "vacations",
  "vacation_san_antonio"   , "vacations",
  "vacation_carolina"      , "vacations",
  "vacation_louisville"    , "vacations",
  "vacation_twin_falls"    , "vacations",
  "vacation_park_city_mckenzie", "vacations",
  "becks_kids"             , "family",
  "vacation_gus"           , "vacations",
  "vacation_yellowstone3"  , "vacations",
  "baby_blessing"          , "holidays"
)




categories_together <- jan_categories %>% 
  bind_rows(feb_categories) %>% 
  bind_rows(mar_categories) %>% 
  bind_rows(apr_categories) %>% 
  bind_rows(may_categories) %>% 
  bind_rows(jun_categories) %>% 
  bind_rows(jul_categories) %>% 
  bind_rows(aug_categories) %>% 
  bind_rows(sep_categories) %>% 
  bind_rows(oct_categories) %>% 
  bind_rows(nov_categories) %>% 
  bind_rows(dec_categories)

categories_together_cleaned <- categories_together %>%
  left_join(wrap_up_categories, by = c("category" = "current_category")) %>% 
  mutate(category = coalesce(new_category, category)) %>% 
  select(-new_category) %>% 
  group_by(category) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE))) %>% 
  ungroup() %>% 
  mutate(across(where(is.numeric), ~replace_na(.,0))) %>% 
  mutate(total_amt_spent = rowSums(across(starts_with("amt_spent")), na.rm = TRUE),
         avg_amt_spent = rowMeans(across(starts_with("amt_spent")), na.rm = TRUE),
         avg_amt_spent = round(avg_amt_spent, 2)
  ) %>% 
  arrange(desc(total_amt_spent))

# View overall what we've been doing
names(categories_together_cleaned) <- str_to_title(gsub("_"," ", gsub("amt_spent_","",names(categories_together_cleaned))))
```

```{r Current Update Data Creation}

```

```{r Vacation Breakdowns}
relevant_vactions_2023_info <- tribble(
  ~place,            ~amount, ~category,     
  "delta (flights)",            136.30, "vacation_carolina",
  "delta (flights)",            286.30, "vacation_carolina",
  "delta (flights)",            250.00, "vacation_carolina",
  "interval (hotel_week)",         198.00, "vacation_carolina",
  "southwest (flights)",       345.18, "vacation_san_antonio",
  "interval (hotel week)",        229.00, "vacation_san_antonio"
) %>% 
  mutate(month = "2023")


vacation_breakdown <- all_months_stacked %>% 
  bind_rows(relevant_vactions_2023_info) %>% 
  left_join(wrap_up_categories, by = c("category" = "current_category")) %>% 
  filter(new_category == "vacations") %>% 
  group_by(category) %>% 
  mutate(total_amt = sum(amount)) %>% 
  ungroup() %>% 
  arrange(desc(total_amt), desc(amount)) %>% 
  mutate(
    category = str_to_title(trimws(gsub("vacation","",gsub("_"," ", category))))
  ) %>% 
  select(category, place, amount) 


```

```{r Specific Vacations}
# Texas
texas_vaca <- specific_vaca_function(all_months_stacked, relevant_vactions_2023_info, "vacation_san_antonio")

# Carolina Vacation
carolina_vaca <- specific_vaca_function(all_months_stacked, relevant_vactions_2023_info, "vacation_carolina")


```

```{r Holiday Breakdowns}
holiday_breakdown <- all_months_stacked %>% 
  left_join(wrap_up_categories, by = c("category" = "current_category")) %>% 
  filter(new_category == "holidays") %>% 
  group_by(category) %>% 
  mutate(total_amt = sum(amount)) %>% 
  ungroup() %>% 
  arrange(desc(total_amt)) %>% 
  select(-new_category, -month, - total_amt)

```

<!-- One Off Data Preparation -->
  
```{r Large Expense Planning}


```

```{r recover, eval=FALSE}

# Credit Card Debt
cc_debt <- 5071.05

# Amount in Bank Account
current_bank <- 1986.02

# Amount coming in Dec 1st
monthly_pay <- 3736*2


# Amount will spend (house_payment + house_essential + subscription + car payment + formula/diapers + gas)
spending <- 3487.68 + 360 + 185 + 340 + 200 + 300

# Amount we have to work with
amount_to_work_with <- monthly_pay*3 + current_bank - spending*3

amount_to_work_with - cc_debt


```


<!-- Data Display -->
  
# Year To Date
```{r create ytd reactable}
yearly_reactable <- categories_together_cleaned %>% 
  mutate(Category = str_to_title(gsub("_"," ",Category))) %>% 
  reactable(
    height = 725,
    defaultPageSize = 50, # Display all rows
    columns = list(
      Category          = colDef(sticky = "left",footer = "Total", format = colFormat(currency = "USD"), filterable = TRUE),
      `Total Amt Spent` = colDef(sticky = "right", footer = function(values) sprintf("$%.2f", sum(values)), format = colFormat(currency = "USD")),
      `Avg Amt Spent`   = colDef(sticky = "right", footer = function(values) sprintf("$%.2f", sum(values)), format = colFormat(currency = "USD")),
      Jan       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Feb       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Mar       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Apr       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      May       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Jun       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Jul       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Aug       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Sep       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Oct       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Nov       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values))),
      Dec       = colDef(format = colFormat(currency = "USD"), footer = function(values) sprintf("$%.2f", sum(values)))
    )
  )
```

```{r Yearly Aggregate Display}
yearly_reactable
```

# Time Comparisons {.tabset}
## Month

Previous Month {Left} vs Current Month {Right}

```{r Month Comparison}
fluidRow(
  column(6, wrap_up_reactable(oct_purchases)),
  column(6, wrap_up_reactable(nov_purchases))
)

```


# Category Review {.tabset}

## Vacations {.tabset}

### Overall

```{r overall}
reactable(
  vacation_breakdown,
  groupBy = "category",
  columns = list(
    amount = colDef(aggregate = "sum", 
                    format = colFormat(currency = "USD"),
                    footer = function(values) sprintf("$%.2f", sum(values))),
    category = colDef(footer = "Total")
  )
)
```

### Texas

```{r texas}
specific_vaca_reactable(texas_vaca)
```

### Carolina

```{r carolina}
specific_vaca_reactable(carolina_vaca)
```

## Holidays

```{r holiday review}
reactable(
  holiday_breakdown,
  groupBy = "category",
  columns = list(
    amount = colDef(aggregate = "sum", 
                    format = colFormat(currency = "USD"), 
                    footer = function(values) sprintf("$%.2f", sum(values))),
    category = colDef(footer = "Total")
  )
)
```

## Subscriptions

```{r subscription review}
all_months_stacked %>% 
  filter(category == "subscription") %>% 
  select(-category) %>% 
  mutate(amount2 = amount) %>% 
  select(amount2, amount, everything()) %>% 
  mutate(place = str_to_title(gsub("_", " ", place))) %>% 
  reactable(
    groupBy = c("place", "month"),
    columns = list(
      place = colDef(name = "Place", footer = "Total"),
      amount = colDef(name = "Total Amount Spent", 
                      aggregate = "sum", 
                      format = colFormat(currency = "USD"),
                      footer = function(values) sprintf("$%.2f", sum(values))
      ),
      amount2 = colDef(name = "Avg Amount Spent", 
                       aggregate = "mean", 
                       format = colFormat(currency = "USD")
      )
    ),
    defaultSorted = list(amount = "desc"),
    height = 500,
    pagination = FALSE
  ) 
```





```{r display grocery gas, eval=FALSE}
grocery_gas_budget %>% 
  arrange() %>% 
  reactable(
    groupBy = c("budget", "category"),
    columns = list(
      budget = colDef(name = "Budget", footer = "Total:"),
      category = colDef(name = "Category"),
      place = colDef(name = "Place"),
      amount = colDef(
        name = "Amount",
        aggregate = "sum", 
        format = colFormat(currency = "USD"), 
        footer = function(values) sprintf("$%.2f", sum(values))
      )
    ),
    pagination = FALSE
  )
```


<!-- Random Other Things -->
  
```{r Debts, eval = FALSE}
debts_df <- tribble(
  ~who,             ~amount, ~min_payment,  ~category,
  "Mick",              7000,            0,  "Fence",
  "Mick",              4000,            0,  "Marriott_Weeks",
  "Aidvantage",       11883,           23,  "Student_Loans",
  "Church",           24300,            0,  "Tithing", # As of End of August 23
  #"American_Express",  1106,          400,  "Credit_Card"
)
```

```{r Sandbox, eval = FALSE}
# California Vacation

april_purchases %>% 
  filter(category == "vacation_cali") %>% 
  mutate(
    sub_category = case_when(place == "disney_land" & amount > 200 ~ "disney_tickets",
                             place == "disney_land" & amount <= 200 ~ "disney_food",
                             place == "target" ~ "misc",
                             TRUE ~ "food"),
    disney = if_else(place == "disney_land", "disney", "not_disney")
  ) %>% 
  group_by(
    place,
    disney,
    sub_category
  ) %>% 
  summarise(
    amt_spent = sum(amount)
  ) %>% 
  reactable(
    groupBy = c("disney", "sub_category", "place"),
    columns = list(
      amt_spent = colDef(
        aggregate = "sum", 
        format = colFormat(currency = "USD"),
        footer = function(values) sprintf("$%.2f", sum(values))
      ),
      disney = colDef(footer = "Total")
    ),
    defaultColDef = colDef(footerStyle = list(fontWeight = "bold"))
  )

# From Jan - Aug 15 of the misc purchases are from wal_mart


# Misc Analysis

all_months_stacked %>% 
  filter(category == "misc") %>%
  mutate(month = factor(month, levels = ( all_months_stacked %>% distinct(month) %>% pull()))) %>% 
  group_by(month,place) %>% 
  summarise(
    num_times = n(),
    total_amount = sum(amount)
  ) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = place,
    values_from = c(num_times,total_amount)
  )

# Attempt at figuring out how much we should spend


# Flexible Costs (ranked in order of most important & on going to least)
# baby ~ Historical Monthly Average $700
# house_var ~ Historical Monthly Average $1250 
# personal ~ Historical Monthly Average $150
# date ~ Historical Monthly Average $75
# misc (Need to clean this up in jan)
# clothes (This one shouldn't be as major going forward) {Need to discuss reasonable clothes budget with Maddie}
# football (This one is all paid for)
# photography (Busness expense & expansion tbd...)

flexible_categories <- tribble(
  ~category,     ~expected_amt, ~flexible,
  "baby",        350,           "flexible",
  "clothes",     300,           "flexible",
  "house_var",   150,           "flexible",
  "personal",    100,           "flexible",
  "misc",        250,           "flexible",
  "date",        50,            "flexible"
)

# Vacations
categories_together %>% 
  filter(grepl("vacation", category)) %>% 
  select(category, total_amt_spent)


# Food Costs
# restaurant 
# grocery

wide_food <- all_months_stacked %>% 
  filter(category %in% c("restaurant", "grocery")) %>% 
  group_by(category, month) %>% 
  summarise(amt_spent = sum(amount)) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = "category",
    values_from = "amt_spent"
  )


all_months_stacked %>% 
  filter(category %in% c("restaurant", "grocery")) %>% 
  mutate(category = "food") %>% 
  group_by(category, month) %>% 
  summarise(amt_spent = sum(amount)) %>% 
  ungroup() %>% 
  left_join(wide_food, by = "month") %>% 
  arrange(desc(amt_spent)) %>% 
  select(
    month,
    grocery,
    restaurant,
    "total_amt_spent" = amt_spent
  )

# Reasonable Food Goal Could Be ?$600?


# Inflexable Costs
# min_house_payment  $3500
# house_essential ~ $400
# car ~ $400
# gas ~ $250
# phone ~ $100
# subscription ~ $75
# BUFFER - $275

inflexible_categories <- tribble(
  ~category,         ~expected_amt, ~flexible,
  "house_essential", 400,           "inflexible",
  "car",             400,           "inflexible",
  "gas",             250,           "inflexible",
  "subscription",    100,           "inflexible",
  "subscription",    75,            "inflexible",
  "buffer",          275,           "inflexible",
  "restaurant",      300,           "inflexible",
  "grocery",         300,           "inflexible"
)

# total inflexable: $3500 + $1500 = $5000

# Overall including food: $5000 + $600 = $5600


# Amount I bring in per month (snap base pay)
# 8200

# Inflexable minus amount brought in
8200 - 5600

# Amount left over for Flexible Costs $2600!



```


